[package]
name = "ragnarok-client"
version = "0.1.0"
edition = "2024"

[dependencies]
ragnarok-formats = { workspace = true }
ragnarok-resources = { workspace = true }
ragnarok-renderer = { workspace = true }
ragnarok-game = { workspace = true }
ragnarok-ai = { workspace = true }
ragnarok-network = { workspace = true }
ragnarok-profiling = { workspace = true }
ragnarok-ui = { workspace = true }
ragnarok-ui-component = { workspace = true }
ragnarok-audio = { workspace = true }
models = { workspace = true }
glam = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
winit = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
ragnarok-ui = { workspace = true, features = ["test-support"] }

[features]
profiling = ["ragnarok-profiling/profiling", "ragnarok-profiling/puffin"]
