use models::enums::effect_id::EffectId;

use super::spec::{AlphaKeyframe, CurveParams, SprBurstParams};

const FIREFLY_ALPHA_KEYFRAMES: &[AlphaKeyframe] = &[
    AlphaKeyframe {
        at_frame: 0,
        alpha_init: 0.0,
        alpha_max: 80.0 / 255.0,
    },
    AlphaKeyframe {
        at_frame: 40,
        alpha_init: 120.0 / 255.0,
        alpha_max: 200.0 / 255.0,
    },
    AlphaKeyframe {
        at_frame: 100,
        alpha_init: 0.0,
        alpha_max: 80.0 / 255.0,
    },
];

pub fn spr_burst_params(id: EffectId) -> Option<(&'static str, SprBurstParams)> {
    match id {
        EffectId::Smoke => Some((
            ragnarok_resources::sprite::effect::CHIMNEY_SMOKE,
            SprBurstParams {
                particle_lifetime_ms: 833.0,
                size: 1.5,
                alpha_max: 1.0,
                burst_count_range: (1, 4),
                speed_range: (0.3, 0.6),
                anim_speed: 4.0,
                pos_y_start: -9.0,
                spawn_radius_xz: 0.0,
                period_frames: None,
                follow_camera: false,
                gravity_world_per_sec2: 0.0,
                cone_latitude_deg: None,
                size_shrink: false,
                twinkle: false,
                curve: None,
                alpha_keyframes: &[],
            },
        )),
        EffectId::Pattack | EffectId::Enchantpoison | EffectId::EnchantpoisonFlow => Some((
            ragnarok_resources::sprite::effect::PARTICLE3,
            SprBurstParams {
                particle_lifetime_ms: 666.0,
                size: 0.65,
                alpha_max: 1.0,
                burst_count_range: (1, 1),
                speed_range: (0.3, 0.6),
                anim_speed: 4.0,
                pos_y_start: 0.0,
                spawn_radius_xz: 8.0,
                period_frames: Some(5),
                follow_camera: false,
                gravity_world_per_sec2: 0.0,
                cone_latitude_deg: None,
                size_shrink: false,
                twinkle: false,
                curve: None,
                alpha_keyframes: &[],
            },
        )),
        EffectId::Detoxication => Some((
            ragnarok_resources::sprite::effect::PARTICLE2,
            SprBurstParams {
                particle_lifetime_ms: 666.0,
                size: 0.6,
                alpha_max: 1.0,
                burst_count_range: (1, 1),
                speed_range: (0.3, 0.6),
                anim_speed: 4.0,
                pos_y_start: 0.0,
                spawn_radius_xz: 8.0,
                period_frames: Some(5),
                follow_camera: false,
                gravity_world_per_sec2: 0.0,
                cone_latitude_deg: None,
                size_shrink: false,
                twinkle: false,
                curve: None,
                alpha_keyframes: &[],
            },
        )),
        EffectId::Snow => Some((
            ragnarok_resources::sprite::effect::EF_SNOW,
            SprBurstParams {
                particle_lifetime_ms: 5333.0,
                size: 0.7,
                alpha_max: 0.6,
                burst_count_range: (2, 2),
                speed_range: (-0.5, -0.5),
                anim_speed: 4.0,
                pos_y_start: -100.0,
                spawn_radius_xz: 300.0,
                period_frames: Some(1),
                follow_camera: true,
                gravity_world_per_sec2: 0.0,
                cone_latitude_deg: None,
                size_shrink: false,
                twinkle: false,
                curve: None,
                alpha_keyframes: &[],
            },
        )),
        EffectId::Firefly => Some((
            ragnarok_resources::sprite::effect::PARTICLE1,
            SprBurstParams {
                particle_lifetime_ms: 2333.0,
                size: 0.65,
                alpha_max: 0.8,
                burst_count_range: (1, 1),
                speed_range: (0.15, 0.5),
                anim_speed: 2.0,
                pos_y_start: -10.0,
                spawn_radius_xz: 8.0,
                period_frames: None,
                follow_camera: false,
                gravity_world_per_sec2: 0.0,
                cone_latitude_deg: Some((0.0, 180.0)),
                size_shrink: false,
                twinkle: true,
                curve: Some(CurveParams {
                    initial_period_frames: (5, 30),
                    subsequent_period_frames: (5, 15),
                    angle_jitter_deg: 40.0,
                    speed_resample: true,
                }),
                alpha_keyframes: FIREFLY_ALPHA_KEYFRAMES,
            },
        )),
        EffectId::Steal => Some((
            ragnarok_resources::sprite::effect::PARTICLE7,
            SprBurstParams {
                particle_lifetime_ms: 500.0,
                size: 1.5,
                alpha_max: 1.0,
                burst_count_range: (10, 10),
                speed_range: (0.5, 1.0),
                anim_speed: 4.0,
                pos_y_start: -10.0,
                spawn_radius_xz: 0.0,
                period_frames: None,
                follow_camera: false,
                gravity_world_per_sec2: 36.0,
                cone_latitude_deg: Some((40.0, 140.0)),
                size_shrink: true,
                twinkle: false,
                curve: None,
                alpha_keyframes: &[],
            },
        )),
        EffectId::Slowpoison => Some((
            ragnarok_resources::sprite::effect::PARTICLE3,
            SprBurstParams {
                particle_lifetime_ms: 666.0,
                size: 0.65,
                alpha_max: 1.0,
                burst_count_range: (1, 1),
                speed_range: (-0.6, -0.3),
                anim_speed: 4.0,
                pos_y_start: -20.0,
                spawn_radius_xz: 8.0,
                period_frames: Some(5),
                follow_camera: false,
                gravity_world_per_sec2: 0.0,
                cone_latitude_deg: None,
                size_shrink: false,
                twinkle: false,
                curve: None,
                alpha_keyframes: &[],
            },
        )),
        EffectId::Edp => Some((
            ragnarok_resources::sprite::effect::PARTICLE3,
            SprBurstParams {
                particle_lifetime_ms: 666.0,
                size: 0.3,
                alpha_max: 1.0,
                burst_count_range: (1, 1),
                speed_range: (0.3, 0.8),
                anim_speed: 4.0,
                pos_y_start: 0.0,
                spawn_radius_xz: 8.0,
                period_frames: Some(3),
                follow_camera: false,
                gravity_world_per_sec2: 0.0,
                cone_latitude_deg: None,
                size_shrink: false,
                twinkle: false,
                curve: None,
                alpha_keyframes: &[],
            },
        )),
        _ => None,
    }
}
