use models::enums::effect_id::EffectId;

pub fn str_aliases(id: EffectId) -> &'static [&'static str] {
    match id {
        EffectId::Coin => &["maemor"],
        EffectId::Steal => &["steal"],
        EffectId::Pattack => &["pattack"],
        EffectId::Detoxication => &["detoxication"],
        EffectId::Stonecurse => &["StoneCurse"],
        EffectId::Firewall => &["newfirewall", "firewall1", "firewall2"],
        EffectId::Lightbolt => &["Lightning", "windhit1", "windhit2", "windhit3"],
        EffectId::Thunderstorm => &["thunderstorm"],
        EffectId::Aqua => &["aqua"],
        EffectId::Signum => &["Cross"],
        EffectId::Angelus => &["Angelus"],
        EffectId::Smoke => &["smoke"],
        EffectId::Firefly => &["firefly"],
        EffectId::Torch => &["torch"],
        EffectId::Firehit => &["firehit1", "firehit2", "firehit3"],
        EffectId::Windhit => &["windhit1", "windhit2", "windhit3"],
        EffectId::Poisonhit => &["poisonhit"],
        EffectId::Arrowshot => &["ArrowShot"],
        EffectId::Invenom => &["Invenom"],
        EffectId::Cure => &["Cure"],
        EffectId::Provoke => &["Provoke"],
        EffectId::Mvp => &["Mvp"],
        EffectId::Skidtrap => &["SkidTrap"],
        EffectId::Brandishspear => &["Brandish"],
        EffectId::Gloria => &["Gloria"],
        EffectId::Magnificat => &["Magnificat"],
        EffectId::Resurrection => &["Resurrection"],
        EffectId::Recovery => &["Recovery"],
        EffectId::Sanctuary => &["Sanctuary"],
        EffectId::Impositio => &["Impositio"],
        EffectId::Lexaeterna => &["LexAeterna"],
        EffectId::Aspersio => &["Aspersio"],
        EffectId::Lexdivina => &["LexDivina"],
        EffectId::Suffragium => &["Suffragium"],
        EffectId::Lord => &["Lord"],
        EffectId::Benedictio => &["Benedictio"],
        EffectId::Meteorstorm => &["meteor1", "meteor2", "meteor3", "meteor4"],
        EffectId::Quagmire => &["Quagmire"],
        EffectId::Firepillar => &["FirePillar"],
        EffectId::Firepillarbomb => &["FirePillarBomb"],
        EffectId::Repairweapon => &["RepairWeapon"],
        EffectId::Crashearth => &["CrashEarth"],
        EffectId::Perfection => &["WeaponPerfection"],
        EffectId::Maxpower => &["MaximizePower"],
        EffectId::Blastmine => &["blastmine"],
        EffectId::Blastminebomb => &["BlastMine"],
        EffectId::Claymore => &["Claymore"],
        EffectId::Freezing => &["Freezing"],
        EffectId::Bubble => &["bubble1", "bubble2", "bubble3", "bubble4"],
        EffectId::Gaspush => &["GasPush"],
        EffectId::Springtrap => &["Spring"],
        EffectId::Kyrie => &["Kyrie"],
        EffectId::Magnus => &["Magnus"],
        EffectId::Venomdust => &["VenomDust"],
        EffectId::Enchantpoison => &["enchantpoison"],
        EffectId::Poisonreact => &["PoisonReact_1st"],
        EffectId::Poisonreact2 => &["PoisonReact", "poisonreact_1st"],
        EffectId::Splasher => &["VenomSplasher"],
        EffectId::Autocounter => &["AutoCounter"],
        EffectId::Freeze => &["Freeze"],
        EffectId::Freezed => &["Freezed"],
        EffectId::Icecrash => &["IceCrash"],
        EffectId::Slowpoison => &["slowp"],
        EffectId::Sandman => &["SandMan"],
        EffectId::Pneuma => &["pneuma1", "pneuma2", "pneuma3"],
        EffectId::Sonicblow2 => &["SonicBlow"],
        EffectId::Brandish2 => &["Brandish2"],
        EffectId::Shockwave => &["ShockWave"],
        EffectId::Shockwavehit => &["ShockWaveHit"],
        EffectId::Earthhit => &["EarthHit"],
        EffectId::Pierceself => &["Pierce"],
        EffectId::Bowlingself => &["Bowling"],
        EffectId::Spearstabself => &["SpearStab"],
        EffectId::Spearbmrself => &["SpearBoomerang"],
        EffectId::Holyhit => &["HolyHit"],
        EffectId::Concentration => &["Concentration"],
        EffectId::Refineok => &["bs_RefineSuccess"],
        EffectId::Refinefail => &["bs_RefineFailed"],
        EffectId::Lvup => &["LevelUP", "h_levelup"],
        EffectId::Joblvup => &["joblvup"],
        // EffectId::Tamingsuccess => &["TamingSuccess"],
        // EffectId::Tamingfailed => &["TamingFailed"],
        EffectId::Mentalbreak => &["MentalBreak"],
        EffectId::Magicalatthit => &["magical"],
        EffectId::SuiExplosion => &["sui_explosion"],
        EffectId::Suicide => &["suicide"],
        EffectId::Comboattack1 => &["yunta_1"],
        EffectId::Comboattack2 => &["yunta_2"],
        EffectId::Comboattack3 => &["yunta_3"],
        EffectId::Comboattack4 => &["yunta_4"],
        EffectId::Comboattack5 => &["yunta_5"],
        EffectId::Guidedattack => &["homing"],
        EffectId::Poisonattack => &["poison"],
        EffectId::Silenceattack => &["silence"],
        EffectId::Stunattack => &["stun"],
        EffectId::Petrifyattack => &["StoneCurse"],
        EffectId::Sleepattack => &["sleep"],
        EffectId::Pong => &["pong1", "pong2", "pong3"],
        EffectId::Potion1 => &["빨간포션", "redpotion"],
        EffectId::Potion2 => &["주홍포션", "scarletpotion"],
        EffectId::Potion3 => &["노란포션", "yellowpotion"],
        EffectId::Potion4 => &["하얀포션", "whitepotion"],
        EffectId::Potion5 => &["파란포션", "bluepotion"],
        EffectId::Potion6 => &["초록포션", "greenpotion"],
        EffectId::Potion7 => &["fruit"],
        EffectId::Potion8 => &["fruit_"],
        EffectId::Darkbreath => &["darkbreath"],
        EffectId::Deffender => &["Deffender"],
        EffectId::Keeping => &["Keeping"],
        EffectId::PotionCon => &["집중", "concentration2"],
        EffectId::Potion => &["각성", "awakening"],
        EffectId::Spellbreaker => &["spell"],
        EffectId::Dispell => &["디스펠", "dispelled"],
        EffectId::Magicrod => &["매직로드", "magicroad_silvery"],
        EffectId::Holycross => &["holy_cross"],
        EffectId::Shieldcharge => &["shield_charge"],
        EffectId::Devotion => &["devotion"],
        EffectId::Flamelauncher => &["enc_fire"],
        EffectId::Frostweapon => &["enc_ice"],
        EffectId::Lightningloader => &["enc_wind"],
        EffectId::Seismicweapon => &["enc_earth"],
        // EffectId::Chimto => &["chimto"],
        EffectId::Stealcoin => &["steal_coin"],
        EffectId::Stripweapon => &["strip_weapon"],
        EffectId::Stripshield => &["strip_shield"],
        EffectId::Striparmor => &["strip_armor"],
        EffectId::Striphelm => &["strip_helm"],
        EffectId::Chaincombo => &["연환", "chaincombo"],
        EffectId::Demonstration => &["demonstration"],
        EffectId::PharmacyOk => &["p_success"],
        EffectId::PharmacyFail => &["p_failed"],
        EffectId::Loud => &["loud"],
        EffectId::Joblvup50 => &["joblvup"],
        EffectId::Angel => &["angel"],
        EffectId::Devil => &["devil"],
        // EffectId::Airtexture => &["airtexture"],
        EffectId::Halfsphere => &["halfsphere"],
        EffectId::Attackenergy => &["attackenergy"],
        EffectId::Attackenergy2 => &["attackenergy2"],
        EffectId::Assumptio2 => &["asum"],
        EffectId::NpcStop => &["npc_stop"],
        EffectId::Soulburn => &["소울번", "soulburn"],
        EffectId::Soulchange => &["사람효과", "effectivepeople"],
        EffectId::Vallentine => &["vallentine"],
        EffectId::Vallentine2 => &["vallentine2"],
        EffectId::Meltdown => &["melt"],
        EffectId::Cartboost => &["cart"],
        EffectId::Rejectsword => &["sword"],
        // EffectId::Flowercast3 => &["flowercast3"],
        EffectId::Mochi => &["찹쌀떡", "waxyriceflour"],
        EffectId::Lamadan => &["ramadan"],
        EffectId::Edp => &["edp"],
        EffectId::Mapae => &["mapae"],
        EffectId::Itempokjuk => &["itempokjuk"],
        EffectId::Itemfast => &["itemfast"],
        EffectId::Ro2year => &["ro2year"],
        EffectId::Hflimoon1 => &["moonlight_1"],
        EffectId::Hflimoon2 => &["moonlight_2"],
        EffectId::Hflimoon3 => &["moonlight_3"],
        EffectId::HoUp => &["h_levelup"],
        EffectId::Hamidefence => &["defense"],
        EffectId::Hamicastle => &["hamicastle"],
        EffectId::Hamiblood => &["hamiblood"],
        EffectId::M01 => &["m01"],
        EffectId::M03 => &["m03"],
        EffectId::M04 => &["m04"],
        EffectId::M05 => &["m05"],
        EffectId::M06 => &["m06"],
        EffectId::M07 => &["m07"],
        EffectId::Food01 => &["food_str"],
        EffectId::Food02 => &["food_int"],
        EffectId::Food03 => &["food_vit"],
        EffectId::Food04 => &["food_agi"],
        EffectId::Food05 => &["food_dex"],
        EffectId::Food06 => &["food_luk"],
        EffectId::Firehit2 => &["firehit1", "firehit2", "firehit3"],
        EffectId::NpcStop2 => &["npc_stop2"],
        EffectId::CookingOk => &["cook_suc"],
        EffectId::CookingFail => &["cook_fail"],
        EffectId::Hapgyeok => &["itempokjuk"],
        EffectId::Kirikage => &["kirikage"],
        EffectId::Tatami => &["tatami"],
        EffectId::Kasumikiri => &["kasumikiri"],
        EffectId::Issen => &["issen"],
        EffectId::Kaen => &["kaen"],
        EffectId::Baku => &["fire dragon"],
        EffectId::Hyousyouraku => &["icy"],
        EffectId::Desperado => &["desperado"],
        EffectId::LightningS => &["lightning_s"],
        EffectId::BlindS => &["blind_s"],
        EffectId::PoisonS => &["poison_s"],
        EffectId::FreezingS => &["freezing_s"],
        EffectId::FlareS => &["flare_s"],
        EffectId::Rapidshower => &["rapidshower"],
        EffectId::Magicalbullet => &["magicalbullet"],
        EffectId::Spreadattack => &["spreadattack"],
        EffectId::Trackcasting => &["트랙킹", "tracking"],
        EffectId::Tracking => &["tracking"],
        EffectId::Tripleaction => &["tripleaction"],
        EffectId::Bullseye => &["불스아이", "bullseye"],
        EffectId::NpcEarthquake => &["npc_earthquake"],
        EffectId::Dragonfear => &["dfear", "dragon_h"],
        EffectId::Wideconfuse => &["dfear"],
        EffectId::Criticalwound => &["cwound"],
        EffectId::PokLove => &["pok_love"],
        EffectId::PokWhite => &["pok_white"],
        EffectId::PokValen => &["pok_valen"],
        EffectId::PokBirth => &["pok_birth"],
        EffectId::PokChristmas => &["pok_christmas"],
        // EffectId::MapMagiczone3 => &["map_magiczone3"],
        // EffectId::MapMagiczone4 => &["map_magiczone4"],
        EffectId::Flowerleaf => &["flower_leaf"],
        EffectId::EnchantpoisonFlow => &["enchantpoison_flow"],
        EffectId::GreenPop => &["Quagmire"],
        EffectId::Levelup => &["levelup", "h_levelup"],
        EffectId::Joblevelup => &["joblevelup", "joblvup"],
        // EffectId::Npcdead => &["npcdead"],
        // EffectId::ClawAtk => &["claw_atk"],
        EffectId::Ring4 => &["ring4"],
        EffectId::Energycoat => &["energycoat"],
        _ => &[],
    }
}

/// Ids whose aliases are interchangeable variants the original game picks
/// between at random on every spawn, rather than a preferred name followed by
/// fallbacks.
pub fn picks_random_variant(id: EffectId) -> bool {
    matches!(
        id,
        EffectId::Firehit
            | EffectId::Firehit2
            | EffectId::Windhit
            | EffectId::Pneuma
            | EffectId::Pong
    )
}

/// The file a spawn shows, given a per-spawn `roll`.
pub fn str_variant(id: EffectId, roll: u64) -> &'static str {
    let names = str_aliases(id);
    match names {
        [] => "",
        [only] => only,
        _ if !picks_random_variant(id) => names[0],
        _ => {
            let scrambled = roll.wrapping_mul(0x9E37_79B9_7F4A_7C15) >> 32;
            names[(scrambled % names.len() as u64) as usize]
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hit_markers_with_variants_spread_across_all_of_them() {
        for id in [EffectId::Firehit, EffectId::Firehit2] {
            assert_eq!(
                str_aliases(id),
                &["firehit1", "firehit2", "firehit3"],
                "{id:?} shares one variant set"
            );
        }
        let picked: std::collections::BTreeSet<&str> = (0..64)
            .map(|roll| str_variant(EffectId::Firehit, roll))
            .collect();
        assert_eq!(picked.len(), 3, "every variant gets used");

        // A single-name effect always resolves to its one file.
        assert_eq!(str_variant(EffectId::Thunderstorm, 7), "thunderstorm");
        // A preferred-name-plus-fallbacks list is not a variant set.
        assert_eq!(str_variant(EffectId::Lightbolt, 7), "Lightning");
    }
}
