[package]
name = "ragnarok-ui-component-hot"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ragnarok-resources = { workspace = true }
models = { workspace = true }
ragnarok-ai = { workspace = true }
ragnarok-ui-component = { workspace = true }
ragnarok-ui = { workspace = true }
ragnarok-game = { workspace = true }
