[package]
name = "ragnarok-ui"
version = "0.1.0"
edition = "2024"

[features]
test-support = []

[dependencies]
ragnarok-renderer = { workspace = true }
ragnarok-resources = { workspace = true }
winit = { workspace = true }
arboard = { version = "3", features = ["wayland-data-control"] }

[target.'cfg(target_os = "linux")'.dependencies]
wayland-client = { workspace = true }
xkbcommon-dl = { workspace = true }
x11rb = { workspace = true }
