#!/usr/bin/env python3
import subprocess, os

REPO = "/home/nmeylan/dev/ragnarok/classic-client"
HANDLER = os.path.join(REPO, "lib/network/src/handler.rs")
OUT = os.path.join(REPO, "lib/network/src/zc_coverage_audit.rs")

# structs that have NO associated packet_id (nested / builder-only sub-structs)
NO_PACKET_ID = {"PacketZcMissionHunt", "PacketZcQuestInfo", "PacketZcQuestMissionInfo"}

names = subprocess.check_output(
    "grep -oE 'PacketZc[A-Za-z0-9]+' " + HANDLER + " | sort -u", shell=True
).decode().split()
names = sorted(set(names))

names_lines = "\n".join('    "{}",'.format(n) for n in names)

arms = []
for n in names:
    idexpr = "None" if n in NO_PACKET_ID else "Some(canon_id({n}::packet_id(v)))".format(n=n)
    # our length = max(base_len, filled): base_len misses scalar nested subs,
    # fill_raw misses fixed-count nested arrays (new() leaves those Vecs empty).
    arms.append('        "{n}" => ({idexpr}, {{ let mut p = {n}::new(v); p.fill_raw_with_packetver(Some(v)); p.raw.len().max({n}::base_len(v)) }}),'.format(n=n, idexpr=idexpr))
arms_lines = "\n".join(arms)

TEMPLATE = r'''// AUTO-GENERATED by lib/network/tools/gen_zc_coverage_audit.py (Step 0 of the
// receive-side packet-version remediation plan). Regenerate when handler.rs
// gains/loses a ZC packet; the test `zc_coverage_audit_drift` fails if this file
// drifts from handler.rs.
//
// Runnable:
//   cargo test -p ragnarok-network zc_coverage_audit -- --nocapture --ignored
//
// It builds the effective server-side ZC id->length table by emulating the C
// preprocessor (MAIN classic build) over three sources -- rathena `packets.hpp`
// (struct sizeof + DEFINE_PACKET_HEADER), Hercules `packets_struct.h`, and legacy
// rathena `clif_packetdb.hpp` -- then compares it against our fully-serialized
// packet length (new + fill_raw_with_packetver) at each target packetver.
#![cfg(test)]
#![allow(clippy::all)]

use packets::packets::*;
use std::collections::BTreeMap;
use std::path::PathBuf;

const TARGETS: &[u32] = &[20120307, 20101124, 20080827, 20070212, 20050719, 20040705];

const CONSUMED_ZC: &[&str] = &[
NAMES_PLACEHOLDER
];

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

// "0xLLHH" wire-byte-concat -> canonical little-endian u16 id
fn canon_id(s: &str) -> u16 {
    let h = s.trim_start_matches("0x").trim_start_matches("0X");
    let b0 = u8::from_str_radix(&h[0..2], 16).unwrap();
    let b1 = u8::from_str_radix(&h[2..4], 16).unwrap();
    (b0 as u16) | ((b1 as u16) << 8)
}

// name -> (id-at-ver, filled-wire-len-at-ver). Length is the fully-serialized size
// (new + fill_raw_with_packetver) so nested fixed sub-structs are counted -- unlike
// base_len(), which returns header-only for such structs. id is None for
// nested/builder-only structs with no PacketId.
fn zc_probe(name: &str, v: u32) -> Option<(Option<u16>, usize)> {
    Some(match name {
ARMS_PLACEHOLDER
        _ => return None,
    })
}

// ---- minimal C-preprocessor emulation (MAIN classic build) ----

#[derive(Clone, Copy)]
struct Frame {
    this_active: bool,
    any_taken: bool,
}

struct Pp {
    stack: Vec<Frame>,
}

impl Pp {
    fn new() -> Self {
        Pp { stack: Vec::new() }
    }
    fn active(&self) -> bool {
        self.stack.iter().all(|f| f.this_active)
    }
    fn parent_active(&self) -> bool {
        self.stack.iter().all(|f| f.this_active)
    }
    fn handle(&mut self, line: &str, target: u32) -> bool {
        // returns true if `line` is a directive (consumed)
        let l = line.trim();
        if l.starts_with("#if ") || l == "#if" || l.starts_with("#ifdef") || l.starts_with("#ifndef") {
            let parent = self.parent_active();
            let cond = if let Some(rest) = l.strip_prefix("#ifndef") {
                !defined(rest.trim())
            } else if let Some(rest) = l.strip_prefix("#ifdef") {
                defined(rest.trim())
            } else {
                eval_cond(l.trim_start_matches("#if"), target)
            };
            let a = parent && cond;
            self.stack.push(Frame { this_active: a, any_taken: a });
            return true;
        }
        if l.starts_with("#elif") {
            if let Some(top) = self.stack.pop() {
                let parent = self.parent_active();
                let cond = eval_cond(l.trim_start_matches("#elif"), target);
                let a = parent && !top.any_taken && cond;
                self.stack.push(Frame { this_active: a, any_taken: top.any_taken || a });
            }
            return true;
        }
        if l.starts_with("#else") {
            if let Some(top) = self.stack.pop() {
                let parent = self.parent_active();
                let a = parent && !top.any_taken;
                self.stack.push(Frame { this_active: a, any_taken: true });
            }
            return true;
        }
        if l.starts_with("#endif") {
            self.stack.pop();
            return true;
        }
        l.starts_with('#')
    }
}

// MAIN classic build: PACKETVER=PACKETVER_MAIN_NUM=target; RE_NUM=ZERO_NUM=0;
// PACKETVER(+_MAIN) defined, RE/ZERO undefined.
fn defined(sym: &str) -> bool {
    let s = sym.trim();
    s == "PACKETVER" || s == "PACKETVER_MAIN"
}

fn eval_cond(expr: &str, target: u32) -> bool {
    let e = expr.trim();
    // handle a leading negation of a (parenthesized) group before splitting
    if let Some(rest) = e.strip_prefix('!') {
        let r = rest.trim();
        let inner = if r.starts_with('(') && r.ends_with(')') {
            &r[1..r.len() - 1]
        } else {
            r
        };
        return !eval_cond(inner, target);
    }
    // OR of AND of atoms
    e.split("||").any(|ort| ort.split("&&").all(|a| eval_atom(a.trim(), target)))
}

fn eval_atom(atom: &str, target: u32) -> bool {
    let a = atom.trim().trim_start_matches('(').trim_end_matches(')').trim();
    if let Some(inner) = a.strip_prefix("defined") {
        let name = inner.trim().trim_start_matches('(').trim_end_matches(')').trim();
        return defined(name);
    }
    if let Some(inner) = a.strip_prefix("!defined") {
        let name = inner.trim().trim_start_matches('(').trim_end_matches(')').trim();
        return !defined(name);
    }
    // <ident> <op> <num>
    for op in ["<=", ">=", "==", "!=", "<", ">"] {
        if let Some(idx) = a.find(op) {
            let lhs = a[..idx].trim();
            let rhs = a[idx + op.len()..].trim();
            let n: u64 = match rhs.parse() {
                Ok(n) => n,
                Err(_) => return false,
            };
            let lv: u64 = match lhs {
                "PACKETVER" | "PACKETVER_MAIN_NUM" => target as u64,
                "PACKETVER_RE_NUM" | "PACKETVER_ZERO_NUM" | "PACKETVER_SAK_NUM" => 0,
                _ => return false,
            };
            return match op {
                "<=" => lv <= n,
                ">=" => lv >= n,
                "==" => lv == n,
                "!=" => lv != n,
                "<" => lv < n,
                ">" => lv > n,
                _ => false,
            };
        }
    }
    false
}

// ---- reference builders ----

#[derive(Clone, Copy, Debug, PartialEq)]
enum RefLen {
    Fixed(i32),
    Var,        // variable-length ([] / PacketLength)
    Unresolved, // sizeof()/unknown sub-struct/unknown array constant
}

#[derive(Clone, Debug)]
struct RefEntry {
    is_cz: bool,
    len: RefLen,
    src: &'static str,
}

// Merged id -> reference at target. Priority: rathena packets.hpp,
// Hercules packets_struct.h, then legacy rathena clif_packetdb.hpp.
fn build_reference(target: u32) -> Option<BTreeMap<u16, RefEntry>> {
    let mut map: BTreeMap<u16, RefEntry> = BTreeMap::new();
    let mut any = false;
    if let Some(m) = parse_struct_source(
        "../../../rathena/src/map/packets.hpp",
        target,
        "ra:packets.hpp",
    ) {
        any = true;
        merge(&mut map, m);
    }
    if let Some(m) = parse_struct_source(
        "../../../Hercules/src/map/packets_struct.h",
        target,
        "he:packets_struct.h",
    ) {
        any = true;
        merge(&mut map, m);
    }
    if let Some(m) = parse_clif_packetdb(target) {
        any = true;
        merge(&mut map, m);
    }
    // gap-fill AMBIG (Unresolved) entries from clif.cpp /// layout comments;
    // do NOT insert absent ids (modern comment layout would false-flag legacy variants).
    if let Some(m) = parse_clif_comments() {
        merge_unresolved(&mut map, m);
    }
    if any { Some(map) } else { None }
}

fn merge_unresolved(dst: &mut BTreeMap<u16, RefEntry>, src: BTreeMap<u16, RefEntry>) {
    for (id, e) in src {
        if let Some(prev) = dst.get(&id) {
            if prev.len == RefLen::Unresolved && e.len != RefLen::Unresolved {
                dst.insert(id, e);
            }
        }
    }
}

// sum `.<count><TYPE>` field tokens (B=1,W=2,L=4,Q=8) in a /// layout string
fn sum_layout_tokens(s: &str) -> usize {
    let b = s.as_bytes();
    let mut total = 0usize;
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'.' {
            let mut j = i + 1;
            let mut count = 0usize;
            let mut has_digit = false;
            while j < b.len() && b[j].is_ascii_digit() {
                count = count * 10 + (b[j] - b'0') as usize;
                j += 1;
                has_digit = true;
            }
            if j < b.len() {
                let base = match b[j] {
                    b'B' => Some(1usize),
                    b'W' => Some(2),
                    b'L' => Some(4),
                    b'Q' => Some(8),
                    _ => None,
                };
                let end_ok = j + 1 >= b.len() || !(b[j + 1] as char).is_ascii_alphanumeric();
                if let (Some(base), true) = (base, end_ok) {
                    let c = if has_digit && count > 0 { count } else { 1 };
                    total += c * base;
                    i = j + 1;
                    continue;
                }
            }
        }
        i += 1;
    }
    total
}

fn clif_layout_len(body: &str) -> RefLen {
    let lower = body.to_ascii_lowercase();
    if lower.contains("*?") || lower.contains("<packet len") || lower.contains("<len>")
        || lower.contains("<length")
    {
        return RefLen::Var;
    }
    let mut extra = 0usize;
    let mut idx = 0;
    while let Some(pos) = body[idx..].find("}*") {
        let p = idx + pos;
        let num: String = body[p + 2..].chars().take_while(|c| c.is_ascii_digit()).collect();
        if num.is_empty() {
            return RefLen::Var;
        }
        let n: usize = num.parse().unwrap_or(1);
        if let Some(open) = body[..p].rfind('{') {
            let bs = sum_layout_tokens(&body[open + 1..p]);
            extra += bs.saturating_mul(n.saturating_sub(1));
        }
        idx = p + 2;
    }
    RefLen::Fixed((2 + sum_layout_tokens(body) + extra) as i32)
}

// rathena clif.cpp `/// <id> <fields...> (NAME)` doc-comments -> id -> length.
// Not version-gated (modern layout); used only to fill AMBIG gaps.
fn parse_clif_comments() -> Option<BTreeMap<u16, RefEntry>> {
    let text = std::fs::read_to_string(manifest_dir().join("../../../rathena/src/map/clif.cpp")).ok()?;
    let mut map: BTreeMap<u16, RefEntry> = BTreeMap::new();
    for raw in text.lines() {
        let t = raw.trim();
        let rest = match t.strip_prefix("/// ") {
            Some(r) => r,
            None => continue,
        };
        let mut it = rest.splitn(2, ' ');
        let id_tok = it.next().unwrap_or("");
        let body_all = it.next().unwrap_or("");
        if id_tok.len() != 4 || !id_tok.bytes().all(|c| c.is_ascii_hexdigit()) {
            continue;
        }
        let id = match u16::from_str_radix(id_tok, 16) {
            Ok(v) => v,
            Err(_) => continue,
        };
        // strip trailing (NAME) and detect direction
        let (body, name) = match body_all.rfind('(') {
            Some(o) => (&body_all[..o], &body_all[o + 1..]),
            None => (body_all, ""),
        };
        let is_cz = name.starts_with("CZ_");
        map.entry(id).or_insert(RefEntry {
            is_cz,
            len: clif_layout_len(body),
            src: "ra:clif.cpp",
        });
    }
    Some(map)
}

fn merge(dst: &mut BTreeMap<u16, RefEntry>, src: BTreeMap<u16, RefEntry>) {
    for (id, e) in src {
        match dst.get(&id) {
            None => {
                dst.insert(id, e);
            }
            // upgrade a prior unresolved reference to a resolved one
            Some(prev) if prev.len == RefLen::Unresolved && e.len != RefLen::Unresolved => {
                dst.insert(id, e);
            }
            Some(_) => {}
        }
    }
}

// Known array-length constants and cross-file sub-struct sizes (classic band).
fn const_val(s: &str) -> Option<i64> {
    let s = s.trim();
    match s {
        "NAME_LENGTH" => Some(24),
        "MAP_NAME_LENGTH" => Some(12),
        "MAP_NAME_LENGTH_EXT" => Some(16),
        "MESSAGE_SIZE" => Some(80),
        "CHAT_SIZE_MAX" => Some(256),
        "CHATROOM_TITLE_SIZE" => Some(37),
        "TALKBOX_MESSAGE_SIZE" => Some(80),
        _ => parse_int(s).map(|v| v as i64),
    }
}

fn prim_size(t: &str) -> Option<usize> {
    Some(match t {
        "int8" | "uint8" | "char" | "bool" => 1,
        "int16" | "uint16" | "short" => 2,
        "int32" | "uint32" | "int" | "long" | "float" => 4,
        "int64" | "uint64" => 8,
        _ => return None,
    })
}

// Parse a C struct source: PACKET_*_ structs (sizeof) + DEFINE_PACKET_HEADER/ID.
fn parse_struct_source(
    rel: &str,
    target: u32,
    src: &'static str,
) -> Option<BTreeMap<u16, RefEntry>> {
    let text = std::fs::read_to_string(manifest_dir().join(rel)).ok()?;
    let mut sizes: BTreeMap<String, RefLen> = BTreeMap::new();
    sizes.insert("EQUIPSLOTINFO".into(), RefLen::Fixed(8)); // uint16 card[4], classic
    let mut ids: Vec<(String, u16)> = Vec::new();
    let mut pp = Pp::new();

    let mut cur: Option<String> = None;
    let mut acc: i64 = 0;
    let mut is_var = false;
    let mut unresolved = false;

    for raw in text.lines() {
        let line = strip_comment(raw);
        if pp.handle(&line, target) {
            continue;
        }
        if !pp.active() {
            continue;
        }
        let t = line.trim();

        if let Some(d) = parse_define(t) {
            ids.push(d);
            continue;
        }

        if cur.is_none() {
            if let Some(name) = parse_struct_open(t) {
                cur = Some(name);
                acc = 0;
                is_var = false;
                unresolved = false;
            }
            continue;
        }

        // inside a struct body
        if t.starts_with('}') {
            let name = cur.take().unwrap();
            let len = if is_var {
                RefLen::Var
            } else if unresolved {
                RefLen::Unresolved
            } else {
                RefLen::Fixed(acc as i32)
            };
            sizes.insert(name, len);
            continue;
        }
        if let Some(name) = parse_struct_open(t) {
            // inline nested struct definition: treat conservatively as unresolved
            let _ = name;
            unresolved = true;
            continue;
        }
        // a PacketLength field is the canonical marker of a variable-length packet
        if t.to_ascii_lowercase().contains("packetlength") {
            is_var = true;
            continue;
        }
        match field_size(t, &sizes) {
            FieldSize::Bytes(n) => acc += n as i64,
            FieldSize::Var => is_var = true,
            FieldSize::Unresolved => unresolved = true,
            FieldSize::None => {}
        }
    }

    let mut out: BTreeMap<u16, RefEntry> = BTreeMap::new();
    for (name, id) in ids {
        let is_cz = name.starts_with("CZ_");
        let len = sizes
            .get(&format!("PACKET_{}", name))
            .copied()
            .unwrap_or(RefLen::Unresolved);
        out.entry(id).or_insert(RefEntry { is_cz, len, src });
    }
    Some(out)
}

fn parse_define(t: &str) -> Option<(String, u16)> {
    let inner = t
        .strip_prefix("DEFINE_PACKET_HEADER(")
        .or_else(|| t.strip_prefix("DEFINE_PACKET_ID("))?;
    let close = inner.find(')')?;
    let args: Vec<&str> = inner[..close].split(',').map(|s| s.trim()).collect();
    if args.len() < 2 {
        return None;
    }
    let name = args[0].to_string();
    let id = parse_int(args[1])? as u16;
    Some((name, id))
}

fn parse_struct_open(t: &str) -> Option<String> {
    let rest = t.strip_prefix("struct ")?;
    let rest = rest.trim();
    let end = rest
        .find(|c: char| c == '{' || c.is_whitespace())
        .unwrap_or(rest.len());
    let name = &rest[..end];
    if !rest[end..].trim_start().starts_with('{') {
        return None;
    }
    if name.is_empty() {
        return None;
    }
    Some(name.to_string())
}

enum FieldSize {
    Bytes(usize),
    Var,
    Unresolved,
    None,
}

fn field_size(t: &str, sizes: &BTreeMap<String, RefLen>) -> FieldSize {
    let t = t.trim().trim_end_matches(';').trim();
    if t.is_empty() {
        return FieldSize::None;
    }
    let mut toks: Vec<&str> = t.split_whitespace().collect();
    if toks.first() == Some(&"struct") {
        toks.remove(0);
    }
    if toks.len() < 2 {
        return FieldSize::None;
    }
    let ty = toks[0];
    let decl = toks[1..].join("");
    // dimensions in the declarator
    let mut count: i64 = 1;
    let mut rest = decl.as_str();
    while let Some(o) = rest.find('[') {
        let c = match rest[o..].find(']') {
            Some(i) => o + i,
            None => return FieldSize::Unresolved,
        };
        let dim = &rest[o + 1..c];
        if dim.trim().is_empty() {
            return FieldSize::Var;
        }
        match const_val(dim) {
            Some(v) => count *= v,
            None => return FieldSize::Unresolved,
        }
        rest = &rest[c + 1..];
    }
    let base = if let Some(p) = prim_size(ty) {
        p
    } else {
        match sizes.get(ty) {
            Some(RefLen::Fixed(n)) => *n as usize,
            Some(RefLen::Var) => return FieldSize::Var,
            _ => return FieldSize::Unresolved,
        }
    };
    FieldSize::Bytes(base * count as usize)
}

// Resolve version-gated symbolic ids from rathena packets_struct.hpp enum.
fn symbol_ids(target: u32) -> BTreeMap<String, u16> {
    let path = manifest_dir().join("../../../rathena/src/map/packets_struct.hpp");
    let mut map = BTreeMap::new();
    let text = match std::fs::read_to_string(&path) {
        Ok(t) => t,
        Err(_) => return map,
    };
    let mut pp = Pp::new();
    for raw in text.lines() {
        let line = strip_comment(raw);
        if pp.handle(&line, target) {
            continue;
        }
        if !pp.active() {
            continue;
        }
        if let Some(eq) = line.find('=') {
            let name = line[..eq].trim();
            if name.is_empty() || !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
                continue;
            }
            let val = line[eq + 1..].trim().trim_end_matches(',').trim();
            if let Some(id) = parse_int(val) {
                if id <= 0xffff {
                    map.insert(name.to_string(), id as u16);
                }
            }
        }
    }
    map
}

// Legacy rathena clif_packetdb.hpp: cumulative, last-wins packet()/parseable_packet().
fn parse_clif_packetdb(target: u32) -> Option<BTreeMap<u16, RefEntry>> {
    let path = manifest_dir().join("../../../rathena/src/map/clif_packetdb.hpp");
    let text = std::fs::read_to_string(&path).ok()?;
    let syms = symbol_ids(target);
    let mut map: BTreeMap<u16, RefEntry> = BTreeMap::new();
    let mut pp = Pp::new();
    for raw in text.lines() {
        let line = strip_comment(raw);
        if pp.handle(&line, target) {
            continue;
        }
        if !pp.active() {
            continue;
        }
        let t = line.trim();
        let is_cz = t.starts_with("parseable_packet");
        let is_zc = t.starts_with("packet(") || t.starts_with("packet (");
        if !is_cz && !is_zc {
            continue;
        }
        let open = match t.find('(') {
            Some(i) => i,
            None => continue,
        };
        let close = match t.rfind(')') {
            Some(i) => i,
            None => continue,
        };
        let args: Vec<&str> = t[open + 1..close].split(',').map(|s| s.trim()).collect();
        if args.len() < 2 {
            continue;
        }
        let id = match parse_id_or_symbol(args[0], &syms) {
            Some(id) => id,
            None => continue,
        };
        let len = match parse_len(args[1]) {
            Some(-1) => RefLen::Var,
            Some(l) => RefLen::Fixed(l),
            None => RefLen::Unresolved,
        };
        // last-wins within this source
        map.insert(
            id,
            RefEntry {
                is_cz,
                len,
                src: "ra:clif_packetdb.hpp",
            },
        );
    }
    Some(map)
}

fn strip_comment(line: &str) -> String {
    let mut s = line.to_string();
    if let Some(i) = s.find("//") {
        s.truncate(i);
    }
    if let Some(i) = s.find("/*") {
        s.truncate(i);
    }
    s
}

fn parse_int(s: &str) -> Option<u32> {
    let s = s.trim();
    if let Some(h) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u32::from_str_radix(h, 16).ok()
    } else {
        s.parse::<u32>().ok()
    }
}

fn parse_id_or_symbol(s: &str, syms: &BTreeMap<String, u16>) -> Option<u16> {
    let s = s.trim();
    if s.starts_with("0x") || s.starts_with("0X") {
        parse_int(s).map(|v| v as u16)
    } else if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        parse_int(s).map(|v| v as u16)
    } else {
        syms.get(s).copied()
    }
}

fn parse_len(s: &str) -> Option<i32> {
    let s = s.trim();
    if s.starts_with("sizeof") {
        return None;
    }
    if let Some(h) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        return i32::from_str_radix(h, 16).ok();
    }
    s.parse::<i32>().ok()
}

fn classify(id_opt: Option<u16>, our_len: usize, refmap: &BTreeMap<u16, RefEntry>) -> &'static str {
    let id = match id_opt {
        None => return "NO-ID",
        Some(id) => id,
    };
    match refmap.get(&id) {
        None => "NO-REF",
        Some(e) if e.is_cz => "ID-REUSE",
        Some(e) => match e.len {
            RefLen::Var => "VAR",
            RefLen::Unresolved => "AMBIG",
            RefLen::Fixed(l) => {
                if l as usize == our_len {
                    "OK"
                } else {
                    "MISMATCH"
                }
            }
        },
    }
}

fn expected_str(id_opt: Option<u16>, refmap: &BTreeMap<u16, RefEntry>) -> (String, &'static str) {
    match id_opt.and_then(|id| refmap.get(&id)) {
        None => ("-".into(), "-"),
        Some(e) => {
            let s = match e.len {
                RefLen::Fixed(l) if e.is_cz => format!("cz({})", l),
                RefLen::Fixed(l) => l.to_string(),
                RefLen::Var => "-1".into(),
                RefLen::Unresolved => "?".into(),
            };
            (s, e.src)
        }
    }
}

fn handler_zc_names() -> Vec<String> {
    let text = std::fs::read_to_string(manifest_dir().join("src/handler.rs")).unwrap();
    let mut out = std::collections::BTreeSet::new();
    let bytes = text.as_bytes();
    let needle = b"PacketZc";
    let mut i = 0;
    while i + needle.len() <= bytes.len() {
        if &bytes[i..i + needle.len()] == needle {
            let start = i;
            let mut j = i + needle.len();
            while j < bytes.len()
                && (bytes[j].is_ascii_alphanumeric() || bytes[j] == b'_')
            {
                j += 1;
            }
            out.insert(String::from_utf8_lossy(&bytes[start..j]).to_string());
            i = j;
        } else {
            i += 1;
        }
    }
    out.into_iter().collect()
}

#[test]
fn zc_coverage_audit_drift() {
    // Every ZC name consumed by handler.rs must have a probe arm here.
    let consumed = handler_zc_names();
    std::panic::set_hook(Box::new(|_| {}));
    let missing: Vec<_> = consumed
        .iter()
        .filter(|n| {
            let n = (*n).clone();
            matches!(std::panic::catch_unwind(move || zc_probe(&n, 20120307)), Ok(None))
        })
        .cloned()
        .collect();
    let _ = std::panic::take_hook();
    assert!(
        missing.is_empty(),
        "handler.rs consumes ZC packets not in the audit probe (regenerate zc_coverage_audit.rs): {:?}",
        missing
    );
    assert_eq!(
        consumed.len(),
        CONSUMED_ZC.len(),
        "consumed ZC count drifted from committed list"
    );
}

#[test]
#[ignore = "prints the Step-0 coverage table; run with --ignored --nocapture"]
fn zc_coverage_audit() {
    for &ver in TARGETS {
        let refmap = match build_reference(ver) {
            Some(m) => m,
            None => {
                eprintln!("SKIP {ver}: reference sources (rathena/Hercules) not found");
                continue;
            }
        };
        struct Row {
            name: String,
            id: Option<u16>,
            exp: String,
            src: &'static str,
            our: usize,
            status: &'static str,
        }
        std::panic::set_hook(Box::new(|_| {}));
        let mut rows: Vec<Row> = Vec::new();
        for name in CONSUMED_ZC {
            let probed = std::panic::catch_unwind(|| zc_probe(name, ver).unwrap());
            let (id_opt, our_len, status) = match probed {
                Ok((id_opt, our_len)) => (id_opt, our_len, classify(id_opt, our_len, &refmap)),
                Err(_) => (None, 0usize, "PANIC"),
            };
            let (exp, src) = expected_str(id_opt, &refmap);
            rows.push(Row { name: name.to_string(), id: id_opt, exp, src, our: our_len, status });
        }
        let _ = std::panic::take_hook();
        rows.sort_by_key(|r| (r.id.unwrap_or(0xffff), r.name.clone()));

        use std::collections::BTreeMap as M;
        let mut counts: M<&'static str, usize> = M::new();
        for r in &rows {
            *counts.entry(r.status).or_insert(0) += 1;
        }

        println!("\n================ ZC COVERAGE AUDIT @ packetver {ver} ================");
        println!("{:<7} {:<44} {:>8} {:>9} {:<11} {}", "id", "struct", "exp_len", "base_len", "status", "src");
        for r in &rows {
            if r.status == "OK" {
                continue; // print only the worklist + notable statuses
            }
            let ids = r.id.map(|i| format!("0x{:04x}", i)).unwrap_or("-".into());
            println!("{:<7} {:<44} {:>8} {:>9} {:<11} {}", ids, r.name, r.exp, r.our, r.status, r.src);
        }
        println!("---- summary @ {ver}: {} consumed ----", rows.len());
        for (k, v) in &counts {
            println!("  {:<15} {}", k, v);
        }

        // cross-source disagreements: same id, different resolved fixed length.
        // first-source-wins in the merge above hides these; surface them here.
        let srcs = [
            parse_struct_source("../../../rathena/src/map/packets.hpp", ver, "ra:packets.hpp"),
            parse_struct_source("../../../Hercules/src/map/packets_struct.h", ver, "he:packets_struct.h"),
            parse_clif_packetdb(ver),
        ];
        let consumed_ids: std::collections::BTreeSet<u16> =
            rows.iter().filter_map(|r| r.id).collect();
        println!("---- cross-source length disagreements @ {ver} ----");
        for id in consumed_ids {
            let mut seen: Vec<(&'static str, i32)> = Vec::new();
            for s in srcs.iter().flatten() {
                if let Some(e) = s.get(&id) {
                    if !e.is_cz {
                        if let RefLen::Fixed(l) = e.len {
                            seen.push((e.src, l));
                        }
                    }
                }
            }
            let distinct: std::collections::BTreeSet<i32> =
                seen.iter().map(|(_, l)| *l).collect();
            if distinct.len() > 1 {
                let detail: Vec<String> =
                    seen.iter().map(|(s, l)| format!("{}={}", s, l)).collect();
                println!("  0x{:04x}  {}", id, detail.join("  "));
            }
        }
    }
}

// ================= inverse dispatch-coverage audit =================
// For each ZC packet the client consumes, take the id the SERVER actually emits
// at packetver V (from packets.hpp / packets_struct.h DEFINE ladders) and ask the
// REAL compiled parser what it does with it: dropped (PacketUnknown), or dispatched
// to some struct (and whether that struct's family matches). This is the true
// receive-side MISSING-LADDER check the per-struct length audit cannot express.

fn camel_to_snake_upper(s: &str) -> String {
    let ch: Vec<char> = s.chars().collect();
    let mut out = String::new();
    for (i, &c) in ch.iter().enumerate() {
        if i > 0 && c.is_ascii_uppercase() {
            let prev = ch[i - 1];
            if prev.is_ascii_lowercase() || prev.is_ascii_digit() {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

// "PacketZcItemPickupAck3" -> "ZC_ITEM_PICKUP_ACK" (strip) / "ZC_ITEM_PICKUP_ACK3"
fn to_family(pascal: &str, strip_trailing_digits: bool) -> String {
    let mut body = pascal.strip_prefix("PacketZc").unwrap_or(pascal).to_string();
    if strip_trailing_digits {
        while body.chars().last().map(|c| c.is_ascii_digit()).unwrap_or(false) {
            body.pop();
        }
    }
    format!("ZC_{}", camel_to_snake_upper(&body))
}

fn strip_trailing_digits(s: &str) -> String {
    let mut s = s.to_string();
    while s.chars().last().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.pop();
    }
    s
}

fn consumed_family_set() -> std::collections::BTreeSet<String> {
    let mut set = std::collections::BTreeSet::new();
    for n in CONSUMED_ZC {
        set.insert(to_family(n, false));
        set.insert(to_family(n, true));
    }
    set
}

// active DEFINE (NAME, id) pairs at V from a struct source
fn struct_source_defs(rel: &str, target: u32) -> Vec<(String, u16)> {
    let text = match std::fs::read_to_string(manifest_dir().join(rel)) {
        Ok(t) => t,
        Err(_) => return Vec::new(),
    };
    let mut pp = Pp::new();
    let mut out = Vec::new();
    for raw in text.lines() {
        let line = strip_comment(raw);
        if pp.handle(&line, target) {
            continue;
        }
        if !pp.active() {
            continue;
        }
        if let Some(d) = parse_define(line.trim()) {
            out.push(d);
        }
    }
    out
}

// consumed ZC family NAME -> set of server-active ids at V
fn server_zc_defs(target: u32) -> BTreeMap<String, std::collections::BTreeSet<u16>> {
    let mut map: BTreeMap<String, std::collections::BTreeSet<u16>> = BTreeMap::new();
    for rel in [
        "../../../rathena/src/map/packets.hpp",
        "../../../Hercules/src/map/packets_struct.h",
    ] {
        for (name, id) in struct_source_defs(rel, target) {
            if name.starts_with("ZC_") {
                map.entry(name).or_default().insert(id);
            }
        }
    }
    // entry/itemlist families carry no DEFINE_PACKET_HEADER; their id-per-version
    // lives in the packets_struct.hpp symbolic enums.
    let syms = symbol_ids(target);
    for (symbol, family) in [
        ("idle_unitType", "ZC_NOTIFY_STANDENTRY"),
        ("spawn_unitType", "ZC_NOTIFY_NEWENTRY"),
        ("unit_walkingType", "ZC_NOTIFY_MOVEENTRY"),
        ("inventorylistnormalType", "ZC_NORMAL_ITEMLIST"),
        ("inventorylistequipType", "ZC_EQUIPMENT_ITEMLIST"),
        ("storageListNormalType", "ZC_STORE_NORMAL_ITEMLIST"),
        ("storageListEquipType", "ZC_STORE_EQUIPMENT_ITEMLIST"),
        ("cartlistnormalType", "ZC_CART_NORMAL_ITEMLIST"),
        ("cartlistequipType", "ZC_CART_EQUIPMENT_ITEMLIST"),
        // reliable only because clif.cpp sends these via `p.PacketType = <symbol>`
        // (verified send-path truth); enum symbols with a hardcoded header switch
        // in clif.cpp (skill_entry/status_change/quest*/equipitem) are NOT added --
        // their enum id can diverge from what the send path actually emits.
        ("dropflooritemType", "ZC_ITEM_FALL_ENTRY"),
        ("sendLookType", "ZC_SPRITE_CHANGE"),
        ("useItemAckType", "ZC_USE_ITEM_ACK"),
    ] {
        if let Some(&id) = syms.get(symbol) {
            map.entry(family.to_string()).or_default().insert(id);
        }
    }
    map
}

// what the real compiled parser does with `id` at `v`
enum Dispatch {
    Unknown,
    Struct(String),
}

fn parser_dispatch(id: u16, v: u32) -> Dispatch {
    let mut buf = vec![0u8; 2048];
    buf[0] = (id & 0xff) as u8;
    buf[1] = (id >> 8) as u8;
    let res = std::panic::catch_unwind(|| {
        let p = packets::packets_parser::parse(&buf, v);
        let unknown = p.as_any().downcast_ref::<PacketUnknown>().is_some();
        (unknown, p.name().to_string())
    });
    match res {
        Ok((true, _)) => Dispatch::Unknown,
        Ok((false, name)) => Dispatch::Struct(name),
        // an arm matched but from() panicked on the zeroed stub buffer => covered
        Err(_) => Dispatch::Struct("<matched>".into()),
    }
}

#[test]
#[ignore = "prints the inverse dispatch-coverage table; run with --ignored --nocapture"]
fn zc_dispatch_coverage() {
    let fams = consumed_family_set();
    for &ver in TARGETS {
        let defs = server_zc_defs(ver);
        if defs.is_empty() {
            eprintln!("SKIP {ver}: reference sources not found");
            continue;
        }
        std::panic::set_hook(Box::new(|_| {}));
        let mut dropped: Vec<(String, u16)> = Vec::new();
        let mut misdispatched: Vec<(String, u16, String)> = Vec::new();
        let mut checked = 0usize;
        let mut covered = 0usize;
        for (name, ids) in &defs {
            let consumed =
                fams.contains(name) || fams.contains(&strip_trailing_digits(name));
            if !consumed {
                continue;
            }
            for &id in ids {
                checked += 1;
                match parser_dispatch(id, ver) {
                    Dispatch::Unknown => dropped.push((name.clone(), id)),
                    Dispatch::Struct(got) => {
                        covered += 1;
                        if got != "<matched>" {
                            let got_fam = to_family(&got, true);
                            let want_fam = strip_trailing_digits(name);
                            if got_fam != want_fam {
                                misdispatched.push((name.clone(), id, got));
                            }
                        }
                    }
                }
            }
        }
        let _ = std::panic::take_hook();

        // consumed families with no DEFINE in the reference sources -> the inverse
        // audit cannot verify these (clif_packetdb-only / unnamed); report honestly.
        let mut unchecked: Vec<String> = Vec::new();
        for n in CONSUMED_ZC {
            let fam = to_family(n, true);
            if !defs.contains_key(&fam) && !defs.keys().any(|k| strip_trailing_digits(k) == fam) {
                if !unchecked.contains(&fam) {
                    unchecked.push(fam);
                }
            }
        }
        unchecked.sort();

        dropped.sort();
        misdispatched.sort();
        println!("\n========== ZC DISPATCH COVERAGE @ packetver {ver} ==========");
        println!("consumed families checked (server-active ids): {checked}");
        println!("consumed families NOT in reference DEFINEs (unverifiable here): {}", unchecked.len());
        for u in &unchecked { println!("    UNVERIFIABLE {}", u); }
        println!("covered by parser: {covered}   DROPPED: {}   MISDISPATCH: {}", dropped.len(), misdispatched.len());
        if !dropped.is_empty() {
            println!("-- DROPPED (server emits, parser returns PacketUnknown) --");
            for (name, id) in &dropped {
                println!("  0x{:04x}  {}", id, name);
            }
        }
        if !misdispatched.is_empty() {
            println!("-- MISDISPATCH (parser routes server id to wrong family) --");
            for (name, id, got) in &misdispatched {
                println!("  0x{:04x}  server={:<32} parser->{}", id, name, got);
            }
        }
    }
}
'''

content = TEMPLATE.replace("NAMES_PLACEHOLDER", names_lines).replace("ARMS_PLACEHOLDER", arms_lines)
with open(OUT, "w") as f:
    f.write(content)
print("wrote", OUT, "with", len(names), "names")
