// Pet illustration + accessory-ACT tables (ported from the original client).
// The paths are the exact GRF resource names; missing files fall back at the
// call site (plain mob ACT / Poring illustration).

/// Poring illustration, used when a pet has no dedicated illustration entry.
pub const PET_ILLUST_FALLBACK: &str = ragnarok_resources::ui::illust::PET_PORING;

pub fn pet_illust(mob_id: i16) -> Option<&'static str> {
    match mob_id {
        1002 => Some(ragnarok_resources::ui::illust::PET_PORING),
        1011 => Some(ragnarok_resources::ui::illust::PET_CHONCHON),
        1014 => Some(ragnarok_resources::ui::illust::PET_SPORE),
        1019 => Some(ragnarok_resources::ui::illust::PET_PECOPECO),
        1023 => Some(ragnarok_resources::ui::illust::PET_ORC_WARRIOR),
        1026 => Some(ragnarok_resources::ui::illust::PET_MUNAK),
        1029 => Some(ragnarok_resources::ui::illust::PET_ISIS),
        1031 => Some(ragnarok_resources::ui::illust::PET_POPORING),
        1035 => Some(ragnarok_resources::ui::illust::PET_HUNTER_FLY),
        1040 => Some(ragnarok_resources::ui::illust::PET_GOLEM),
        1042 => Some(ragnarok_resources::ui::illust::PET_STEEL_CHONCHON),
        1049 => Some(ragnarok_resources::ui::illust::PET_PICKY),
        1052 => Some(ragnarok_resources::ui::illust::PET_ROCKER),
        1056 => Some(ragnarok_resources::ui::illust::PET_SMOKIE),
        1057 => Some(ragnarok_resources::ui::illust::PET_YOYO),
        1063 => Some(ragnarok_resources::ui::illust::PET_LUNATIC),
        1077 => Some(ragnarok_resources::ui::illust::PET_POISON_SPORE),
        1101 => Some(ragnarok_resources::ui::illust::PET_BAPHOMET_JR),
        1107 => Some(ragnarok_resources::ui::illust::PET_BABY_DESERT_WOLF),
        1109 => Some(ragnarok_resources::ui::illust::PET_DEVIRUCHI),
        1110 => Some(ragnarok_resources::ui::illust::PET_DOKEBI),
        1113 => Some(ragnarok_resources::ui::illust::PET_DROPS),
        1122 => Some(ragnarok_resources::ui::illust::PET_GOBLIN_DAGGER),
        1123 => Some(ragnarok_resources::ui::illust::PET_GOBLIN_FLAIL),
        1125 => Some(ragnarok_resources::ui::illust::PET_GOBLIN_HAMMER),
        1143 => Some(ragnarok_resources::ui::illust::PET_MARIONETTE),
        1148 => Some(ragnarok_resources::ui::illust::PET_MEDUSA),
        1155 => Some(ragnarok_resources::ui::illust::PET_PETITE),
        1167 => Some(ragnarok_resources::ui::illust::PET_SAVAGE_BABE),
        1170 => Some(ragnarok_resources::ui::illust::PET_SOHEE),
        1179 => Some(ragnarok_resources::ui::illust::PET_WHISPER),
        1188 => Some(ragnarok_resources::ui::illust::PET_BONGUN),
        1200 => Some(ragnarok_resources::ui::illust::PET_ZHERLTHSH),
        1208 => Some(ragnarok_resources::ui::illust::PET_WANDERER),
        1245 => Some(ragnarok_resources::ui::illust::PET_GOBLIN_EVENT),
        1275 => Some(ragnarok_resources::ui::illust::PET_ALICE),
        1299 => Some(ragnarok_resources::ui::illust::PET_GOBLIN_LEADER),
        1370 => Some(ragnarok_resources::ui::illust::PET_SUCCUBUS),
        1374 => Some(ragnarok_resources::ui::illust::PET_INCUBUS),
        1379 => Some(ragnarok_resources::ui::illust::PET_NIGHTMARE_TERROR),
        1382 => Some(ragnarok_resources::ui::illust::PET_DIABOLIC),
        1385 => Some(ragnarok_resources::ui::illust::PET_DELETER),
        1401 => Some(ragnarok_resources::ui::illust::PET_SHINOBI),
        1404 => Some(ragnarok_resources::ui::illust::PET_MIYABI_NINGYO),
        1416 => Some(ragnarok_resources::ui::illust::PET_WICKED_NYMPH),
        1495 => Some(ragnarok_resources::ui::illust::PET_STONE_SHOOTER),
        1504 => Some(ragnarok_resources::ui::illust::PET_DULLAHAN),
        1505 => Some(ragnarok_resources::ui::illust::PET_LOLI_RURI),
        1513 => Some(ragnarok_resources::ui::illust::PET_CIVIL_SERVANT),
        1519 => Some(ragnarok_resources::ui::illust::PET_CHUNG_E),
        1586 => Some(ragnarok_resources::ui::illust::PET_LEAF_CAT),
        1630 => Some(ragnarok_resources::ui::illust::PET_BACSOJIN),
        1815 => Some(ragnarok_resources::ui::illust::PET_RICE_CAKE),
        1837 => Some(ragnarok_resources::ui::illust::PET_IMP),
        1879 => Some(ragnarok_resources::ui::illust::PET_LUNATIC),
        1963 => Some(ragnarok_resources::ui::illust::PET_CHUNG_E),
        2200 => Some(ragnarok_resources::ui::illust::PET_J_TAINI),
        2210 => Some(ragnarok_resources::ui::illust::PET_CHRISTMAS_SNOW_RABBIT),
        _ => None,
    }
}

pub fn pet_accessory_act(view_id: u16) -> Option<&'static str> {
    match view_id {
        10001 => Some(ragnarok_resources::sprite::pet_accessory::BAPHOMET),
        10002 => Some(ragnarok_resources::sprite::pet_accessory::CHOCHO),
        10003 => Some(ragnarok_resources::sprite::pet_accessory::DESERT_WOLF_B),
        10004 => Some(ragnarok_resources::sprite::pet_accessory::DEVIRUCHI),
        10005 => Some(ragnarok_resources::sprite::pet_accessory::DOKEBI),
        10006 => Some(ragnarok_resources::sprite::pet_accessory::ISIS),
        10007 => Some(ragnarok_resources::sprite::pet_accessory::LUNATIC),
        10008 => Some(ragnarok_resources::sprite::pet_accessory::MUNAK),
        10009 => Some(ragnarok_resources::sprite::pet_accessory::ORK_WARRIOR),
        10010 => Some(ragnarok_resources::sprite::pet_accessory::PECOPECO),
        10011 => Some(ragnarok_resources::sprite::pet_accessory::PETIT),
        10012 => Some(ragnarok_resources::sprite::pet_accessory::PICKY),
        10013 => Some(ragnarok_resources::sprite::pet_accessory::PORING),
        10014 => Some(ragnarok_resources::sprite::pet_accessory::ROCKER),
        10015 => Some(ragnarok_resources::sprite::pet_accessory::SAVAGE_BABE),
        10016 => Some(ragnarok_resources::sprite::pet_accessory::SOHEE),
        10017 => Some(ragnarok_resources::sprite::pet_accessory::SPORE),
        10018 => Some(ragnarok_resources::sprite::pet_accessory::YOYO),
        10019 => Some(ragnarok_resources::sprite::pet_accessory::SMOKIE),
        10020 => Some(ragnarok_resources::sprite::pet_accessory::BON_GUN),
        10021 => Some(ragnarok_resources::sprite::pet_accessory::BACSOJIN),
        10022 => Some(ragnarok_resources::sprite::pet_accessory::CIVIL_SERVANT),
        10023 => Some(ragnarok_resources::sprite::pet_accessory::LEAF_CAT),
        10024 => Some(ragnarok_resources::sprite::pet_accessory::LOLI_RURI),
        10025 => Some(ragnarok_resources::sprite::pet_accessory::MARIONETTE),
        10026 => Some(ragnarok_resources::sprite::pet_accessory::SHINOBI),
        10027 => Some(ragnarok_resources::sprite::pet_accessory::WHISPER),
        10028 => Some(ragnarok_resources::sprite::pet_accessory::GOBLIN_LEADER),
        10029 => Some(ragnarok_resources::sprite::pet_accessory::WICKED_NYMPH),
        10030 => Some(ragnarok_resources::sprite::pet_accessory::MIYABI_NINGYO),
        10031 => Some(ragnarok_resources::sprite::pet_accessory::DULLAHAN),
        10032 => Some(ragnarok_resources::sprite::pet_accessory::MEDUSA),
        10033 => Some(ragnarok_resources::sprite::pet_accessory::STONE_SHOOTER),
        10034 => Some(ragnarok_resources::sprite::pet_accessory::INCUBUS),
        10035 => Some(ragnarok_resources::sprite::pet_accessory::GOLEM),
        10036 => Some(ragnarok_resources::sprite::pet_accessory::NIGHTMARE_TERROR),
        10037 => Some(ragnarok_resources::sprite::pet_accessory::SUCCUBUS),
        10038 => Some(ragnarok_resources::sprite::pet_accessory::IMP),
        _ => None,
    }
}
/// Pet emotion table [hunger 0-4][friendly 0-4][act 0-6] -> emotion id (ported).
/// -1 means no emote for that combination.
pub fn pet_emotion(hunger: usize, friendly: usize, act: usize) -> Option<u16> {
    const T: [[[i16; 7]; 5]; 5] = [
        [
            [32, 32, 29, 29, 7, 23, 28],
            [32, 32, 29, 29, 7, 7, 5],
            [20, 32, -1, 32, 5, 20, 10],
            [33, -1, -1, 10, 20, 10, 6],
            [18, -1, -1, 20, 33, 2, 6],
        ],
        [
            [20, 32, 29, 29, 32, 32, 5],
            [20, 32, -1, 32, 29, 32, 32],
            [33, -1, -1, 10, 20, 10, 6],
            [18, -1, -1, 20, 33, 2, 6],
            [15, -1, -1, 19, 3, 2, 21],
        ],
        [
            [32, 32, -1, 32, 29, 5, 32],
            [20, -1, -1, 10, 10, 10, 20],
            [33, -1, -1, 20, 33, 2, 6],
            [18, -1, -1, 19, 18, 2, 21],
            [15, 21, -1, 23, 4, 33, 21],
        ],
        [
            [32, -1, -1, 10, 10, 10, 20],
            [32, -1, -1, 20, 20, 20, 10],
            [20, -1, -1, 19, 21, 2, 6],
            [33, 21, 19, 23, 3, 33, 21],
            [18, 21, 26, 28, 30, 22, 18],
        ],
        [
            [23, -1, -1, 20, 20, 20, 9],
            [32, -1, -1, 19, 20, 0, 0],
            [32, 21, 19, 23, 18, 33, 21],
            [20, 21, 26, 28, 3, 18, 18],
            [20, 21, 26, 28, 30, 18, 30],
        ],
    ];
    let v = *T.get(hunger)?.get(friendly)?.get(act)?;
    (v >= 0).then_some(v as u16)
}
