#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StatusCategory {
    Buff,
    Debuff,
    Toggle,
}

#[derive(Clone, Copy, Debug)]
pub struct StatusIconInfo {
    pub icon: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub category: StatusCategory,
}

pub fn status_icon_info(efst: i16) -> Option<&'static StatusIconInfo> {
    let info: &'static StatusIconInfo = match efst {
        0 => &StatusIconInfo {
            icon: "프로보크.tga",
            name: "Provoke",
            description: "Reduces VIT DEF\nIncreases ATK",
            category: StatusCategory::Buff,
        },
        1 => &StatusIconInfo {
            icon: "인듀어.tga",
            name: "Endure",
            description: "Enables attacking and movement\nwhile receiving damage",
            category: StatusCategory::Buff,
        },
        2 => &StatusIconInfo {
            icon: "투핸드퀴큰.tga",
            name: "Two Hand Quicken",
            description: "When using two handed weapons,\nincreases ASPD",
            category: StatusCategory::Buff,
        },
        3 => &StatusIconInfo {
            icon: "집중력향상.tga",
            name: "Attention Concentration",
            description: "Increases DEX, AGI\nReveals nearby hidden enemies",
            category: StatusCategory::Buff,
        },
        4 => &StatusIconInfo {
            icon: "하이딩.tga",
            name: "Hiding",
            description: "Avoids enemy attacks by hiding in the ground\nCan be discovered with detection skills",
            category: StatusCategory::Buff,
        },
        5 => &StatusIconInfo {
            icon: "클로킹.tga",
            name: "Cloaking",
            description: "Invisible",
            category: StatusCategory::Buff,
        },
        6 => &StatusIconInfo {
            icon: "인찬트포이즌.tga",
            name: "Enchant Poison",
            description: "Enchants Weapon with Poison Property",
            category: StatusCategory::Buff,
        },
        7 => &StatusIconInfo {
            icon: "포이즌리액트.tga",
            name: "Poison React",
            description: "Counters a Poison attack with a one-time attack\nWhen hit by a physical non-poison attack,\nthere is a chance to cast Envenom on target",
            category: StatusCategory::Buff,
        },
        8 => &StatusIconInfo {
            icon: "콰그마이어.tga",
            name: "Quagmire",
            description: "Reduces Movement Speed\nReduces AGI/DEX",
            category: StatusCategory::Debuff,
        },
        9 => &StatusIconInfo {
            icon: "안젤루스.tga",
            name: "Angelus",
            description: "Increases VIT DEF",
            category: StatusCategory::Buff,
        },
        10 => &StatusIconInfo {
            icon: "블레싱.tga",
            name: "Blessing",
            description: "Increases DEX, INT and STR\nRecovers from a few status effects",
            category: StatusCategory::Buff,
        },
        11 => &StatusIconInfo {
            icon: "시그넘크루시스.tga",
            name: "Signum Crucis",
            description: "Reduces Undead and Demon monsters DEF",
            category: StatusCategory::Buff,
        },
        12 => &StatusIconInfo {
            icon: "민첩성증가.tga",
            name: "Increase agility",
            description: "Increases Movement Speed\nIncreases Attack Speed",
            category: StatusCategory::Buff,
        },
        13 => &StatusIconInfo {
            icon: "민첩성감소.tga",
            name: "Decrease Agility",
            description: "Reduces Movement Speed\nReduces ASPD",
            category: StatusCategory::Debuff,
        },
        14 => &StatusIconInfo {
            icon: "슬로우포이즌.tga",
            name: "Slow Poison",
            description: "Temporarily stops Poison Damage",
            category: StatusCategory::Buff,
        },
        15 => &StatusIconInfo {
            icon: "임포시티오마누스.tga",
            name: "Impositio Manus",
            description: "Increases Weapon damage",
            category: StatusCategory::Buff,
        },
        16 => &StatusIconInfo {
            icon: "수줍은하루의우울.tga",
            name: "Suffragium",
            description: "Reduces cast time.",
            category: StatusCategory::Buff,
        },
        17 => &StatusIconInfo {
            icon: "아스페르시오.tga",
            name: "Aspersio",
            description: "Enchants Weapon with Holy Property",
            category: StatusCategory::Buff,
        },
        18 => &StatusIconInfo {
            icon: "성체강복.tga",
            name: "%s",
            description: "Enchants Armor with Holy Property",
            category: StatusCategory::Buff,
        },
        19 => &StatusIconInfo {
            icon: "기리에엘레이손.tga",
            name: "Kyrie Eleison",
            description: "A defensive barrier that blocks a certain number of attacks",
            category: StatusCategory::Buff,
        },
        20 => &StatusIconInfo {
            icon: "마니피캇.tga",
            name: "Magnificat",
            description: "Increases natural SP Recovery Speed",
            category: StatusCategory::Buff,
        },
        21 => &StatusIconInfo {
            icon: "글로리아.tga",
            name: "Gloria",
            description: "Increases LUK",
            category: StatusCategory::Buff,
        },
        22 => &StatusIconInfo {
            icon: "렉스에테르나.tga",
            name: "Lex Aeterna",
            description: "Doubles damage of the next attack",
            category: StatusCategory::Debuff,
        },
        23 => &StatusIconInfo {
            icon: "아드레날린러쉬.tga",
            name: "Adrenaline Rush",
            description: "Increases Attack Speed of\nAxes and Mace weapons",
            category: StatusCategory::Buff,
        },
        24 => &StatusIconInfo {
            icon: "웨폰퍼펙션.tga",
            name: "Weapon Perfection",
            description: "Applies 100% damage to\nsmall, medium and large monsters",
            category: StatusCategory::Buff,
        },
        25 => &StatusIconInfo {
            icon: "오버트러스트.tga",
            name: "Over Thrust",
            description: "Increases weapon damage.\nIncreases the possibility of breaking the weapon.",
            category: StatusCategory::Buff,
        },
        26 => &StatusIconInfo {
            icon: "맥시마이즈파워.tga",
            name: "Maximize Power",
            description: "Increases damage to the maximum\nDrains SP over time",
            category: StatusCategory::Buff,
        },
        27 => &StatusIconInfo {
            icon: "라이딩.tga",
            name: "Riding Vehicle",
            description: "",
            category: StatusCategory::Toggle,
        },
        28 => &StatusIconInfo {
            icon: "팔콘.tga",
            name: "Falconry Mastery",
            description: "Falcon Rental",
            category: StatusCategory::Toggle,
        },
        29 => &StatusIconInfo {
            icon: "죽은척하기.tga",
            name: "Trick Dead (Play Dead)",
            description: "Pretend Dead Status",
            category: StatusCategory::Toggle,
        },
        30 => &StatusIconInfo {
            icon: "고성지르기.tga",
            name: "Loud Exclamation (Crazy Uproar)",
            description: "Increases STR",
            category: StatusCategory::Buff,
        },
        31 => &StatusIconInfo {
            icon: "에너지코트.tga",
            name: "Energy Coat",
            description: "Reduces damage in proportion\nto the amount of SP remaining",
            category: StatusCategory::Buff,
        },
        32 => &StatusIconInfo {
            icon: "갑옷파괴.tga",
            name: "Armor is damaged",
            description: "",
            category: StatusCategory::Debuff,
        },
        33 => &StatusIconInfo {
            icon: "무기파괴.tga",
            name: "Weapon is damaged.",
            description: "",
            category: StatusCategory::Debuff,
        },
        34 => &StatusIconInfo {
            icon: "환각.tga",
            name: "Illusion",
            description: "Screen distortion\nShows more damage\nRandomly interrupts casting",
            category: StatusCategory::Debuff,
        },
        35 => &StatusIconInfo {
            icon: "무게50이상.tga",
            name: "Overweight 50%",
            description: "HP/SP will not be restored",
            category: StatusCategory::Debuff,
        },
        36 => &StatusIconInfo {
            icon: "무게90이상.tga",
            name: "Overweight 90%",
            description: "HP/SP will not be restored\nAttacks/Skills are disabled",
            category: StatusCategory::Debuff,
        },
        37 => &StatusIconInfo {
            icon: "공속물약.tga",
            name: "Concentration Potion",
            description: "Increases ASPD",
            category: StatusCategory::Buff,
        },
        38 => &StatusIconInfo {
            icon: "공속물약.tga",
            name: "Awakening Potion",
            description: "Increases ASPD",
            category: StatusCategory::Buff,
        },
        39 => &StatusIconInfo {
            icon: "공속물약.tga",
            name: "Berserk Potion",
            description: "Increases ASPD",
            category: StatusCategory::Buff,
        },
        41 => &StatusIconInfo {
            icon: "민첩성증가.tga",
            name: "%s",
            description: "Increases Movement Speed",
            category: StatusCategory::Buff,
        },
        42 => &StatusIconInfo {
            icon: "민첩성증가.tga",
            name: "Increases Movement Speed",
            description: "",
            category: StatusCategory::Buff,
        },
        50 => &StatusIconInfo {
            icon: "스트립웨폰.tga",
            name: "Weapon Off Status",
            description: "Weapons cannot be worn",
            category: StatusCategory::Debuff,
        },
        51 => &StatusIconInfo {
            icon: "스트립쉴드.tga",
            name: "Shield Off Status",
            description: "Shields cannot be worn",
            category: StatusCategory::Debuff,
        },
        52 => &StatusIconInfo {
            icon: "스트립아머.tga",
            name: "Armor Off Status",
            description: "Armor cannot be worn",
            category: StatusCategory::Debuff,
        },
        53 => &StatusIconInfo {
            icon: "스트립헬름.tga",
            name: "Headgear Off Status",
            description: "Headgear cannot be worn",
            category: StatusCategory::Debuff,
        },
        54 => &StatusIconInfo {
            icon: "케미컬프로텍션[웨폰].tga",
            name: "Chemical Protection (Weapon)",
            description: "Prevents weapon from being stripped/broken",
            category: StatusCategory::Buff,
        },
        55 => &StatusIconInfo {
            icon: "케미컬프로텍션[쉴드].tga",
            name: "Chemical Protection (Shield)",
            description: "Prevents shield from being stripped/broken",
            category: StatusCategory::Buff,
        },
        56 => &StatusIconInfo {
            icon: "케미컬프로텍션[아머].tga",
            name: "Chemical Protection (Armor)",
            description: "Prevents body Armor from being stripped/broken",
            category: StatusCategory::Buff,
        },
        57 => &StatusIconInfo {
            icon: "케미컬프로텍션[헬름].tga",
            name: "Chemical Protection Helm (Biochemical Helm)",
            description: "Protect helm from being destroyed",
            category: StatusCategory::Buff,
        },
        58 => &StatusIconInfo {
            icon: "오토가드.tga",
            name: "Auto Guard",
            description: "Has a chance to block physical attacks",
            category: StatusCategory::Buff,
        },
        59 => &StatusIconInfo {
            icon: "리플렉트쉴드.tga",
            name: "Reflect Shield",
            description: "When attacked with physical short range attacks\nreflect a portion of the damage",
            category: StatusCategory::Buff,
        },
        61 => &StatusIconInfo {
            icon: "신의뜻.tga",
            name: "Providence",
            description: "Increased resistance\nto undead and demon monsters",
            category: StatusCategory::Buff,
        },
        62 => &StatusIconInfo {
            icon: "디펜더.tga",
            name: "Defender (Defending Aura)",
            description: "Reduce Damage from Ranged Physical Attack\nReduces Movement Speed and Attack Speed",
            category: StatusCategory::Buff,
        },
        64 => &StatusIconInfo {
            icon: "연마제.tga",
            name: "Granted a weapon property",
            description: "",
            category: StatusCategory::Buff,
        },
        65 => &StatusIconInfo {
            icon: "오토스펠.tga",
            name: "Auto Spell",
            description: "When physically attacking\nthe selected skill will automatically cast without casting time.\nSP consumed is 2/3 the regular amount\nSkill will not cast without sufficient SP",
            category: StatusCategory::Buff,
        },
        68 => &StatusIconInfo {
            icon: "스피어퀴큰.tga",
            name: "Spear Quicken",
            description: "Increase ASPD when using Spear\nIncrease Critical rate\nIncrease Flee",
            category: StatusCategory::Buff,
        },
        69 => &StatusIconInfo {
            icon: "바드노래.tga",
            name: "BDPLAYING",
            description: "",
            category: StatusCategory::Buff,
        },
        87 => &StatusIconInfo {
            icon: "steelbody.tga",
            name: "Steel Body",
            description: "Sets DEF and MDEF to a fixed amount.\nReduces Movement Speed and ASPD\nSkills are disabled",
            category: StatusCategory::Buff,
        },
        88 => &StatusIconInfo {
            icon: "extremityfist.tga",
            name: "Asura Strike (Guillotine Fist)",
            description: "SP recovery is disabled",
            category: StatusCategory::Debuff,
        },
        90 => &StatusIconInfo {
            icon: "프레임런쳐.tga",
            name: "Flame Launcher",
            description: "Enchants Weapon with Fire Property",
            category: StatusCategory::Buff,
        },
        91 => &StatusIconInfo {
            icon: "프로스트웨폰.tga",
            name: "Frost Weapon (Endow Tsunami)",
            description: "Enchants Weapon with Water Property",
            category: StatusCategory::Buff,
        },
        92 => &StatusIconInfo {
            icon: "라이트닝로더.tga",
            name: "Lightning Loader",
            description: "Enchants Weapon with Wind Property",
            category: StatusCategory::Buff,
        },
        93 => &StatusIconInfo {
            icon: "사이즈믹웨폰.tga",
            name: "Seismic Weapon",
            description: "Enchants Weapon with Earth Property",
            category: StatusCategory::Buff,
        },
        97 => &StatusIconInfo {
            icon: "bd_undead.tga",
            name: "Enchants Armor with Undead Property",
            description: "",
            category: StatusCategory::Buff,
        },
        104 => &StatusIconInfo {
            icon: "icon10.tga",
            name: "Parrying",
            description: "Blocks physical attacks by chance",
            category: StatusCategory::Buff,
        },
        106 => &StatusIconInfo {
            icon: "icon08.tga",
            name: "Tension Relax",
            description: "Increases natural HP recovery",
            category: StatusCategory::Buff,
        },
        110 => &StatusIconInfo {
            icon: "icon05.tga",
            name: "Assumptio",
            description: "Reduces damage taken",
            category: StatusCategory::Buff,
        },
        112 => &StatusIconInfo {
            icon: "i_장판.tga",
            name: "%s",
            description: "Ground skill effect",
            category: StatusCategory::Buff,
        },
        114 => &StatusIconInfo {
            icon: "i_치독.tga",
            name: "Enchant Deadly Poison",
            description: "Applies a deadly poison to weapon\nDamage increase does not apply to boss monsters",
            category: StatusCategory::Buff,
        },
        115 => &StatusIconInfo {
            icon: "icon09.tga",
            name: "True Sight",
            description: "Increases all stats\nIncreases ATK, HIT, CRIT",
            category: StatusCategory::Buff,
        },
        116 => &StatusIconInfo {
            icon: "icon06.tga",
            name: "Wind Walk",
            description: "Increases Movement Speed/Evasion",
            category: StatusCategory::Buff,
        },
        117 => &StatusIconInfo {
            icon: "icon03.tga",
            name: "Meltdown",
            description: "When attacking a player\nthere is a chance to destroy his/her weapon/armor\nWhen attacking a monster\nthe monster's attack and defense are reduced",
            category: StatusCategory::Buff,
        },
        118 => &StatusIconInfo {
            icon: "icon07.tga",
            name: "Cart Boost",
            description: "Increases Movement Speed",
            category: StatusCategory::Buff,
        },
        120 => &StatusIconInfo {
            icon: "icon04.tga",
            name: "Sword Reject",
            description: "Reflects damage back to attacking monsters\n(for all monster attacks)\nDamage received is reduced by 1/2\nYou receive the other 1/2 of damage",
            category: StatusCategory::Buff,
        },
        121 => &StatusIconInfo {
            icon: "icon01.tga",
            name: "Marionette Control (caster)",
            description: "Passes the stats\nto a Player",
            category: StatusCategory::Buff,
        },
        122 => &StatusIconInfo {
            icon: "icon01.tga",
            name: "Marionette Control (target)",
            description: "Target Player\nwho receives the stats",
            category: StatusCategory::Buff,
        },
        124 => &StatusIconInfo {
            icon: "출혈상태.tga",
            name: "Bleeding",
            description: "HP, SP recovery disabled\nHP lost every 10 seconds",
            category: StatusCategory::Buff,
        },
        125 => &StatusIconInfo {
            icon: "관절공격.tga",
            name: "Joint Beat",
            description: "Applies various status effects\ndue to joint damage.",
            category: StatusCategory::Buff,
        },
        130 => &StatusIconInfo {
            icon: "엄마아빠사랑해요.tga",
            name: "Mom and Dad I Love You",
            description: "No EXP loss upon death",
            category: StatusCategory::Buff,
        },
        132 => &StatusIconInfo {
            icon: "금강불괴.tga",
            name: "Auto Berserk",
            description: "Rage when close to death",
            category: StatusCategory::Buff,
        },
        133 => &StatusIconInfo {
            icon: "i_run.tga",
            name: "RUN",
            description: "",
            category: StatusCategory::Buff,
        },
        135 => &StatusIconInfo {
            icon: "i_stormkick.tga",
            name: "Whirlwind Kick (Tornado Kick)",
            description: "When attacking an enemy\nthere is a chance to prepare a Whirlwind Kick",
            category: StatusCategory::Buff,
        },
        137 => &StatusIconInfo {
            icon: "i_downkick.tga",
            name: "Prepare Down Kick",
            description: "Hit an enemy\nfor a chance to preform a kick",
            category: StatusCategory::Buff,
        },
        139 => &StatusIconInfo {
            icon: "i_turnkick.tga",
            name: "Ready Turn Kick",
            description: "When attacking,\nthere's a chance to prepare a Turn Kick",
            category: StatusCategory::Buff,
        },
        141 => &StatusIconInfo {
            icon: "i_counter.tga",
            name: "Prepare Counter Kick",
            description: "Hit an enemy\nto be ready for a counter kick",
            category: StatusCategory::Buff,
        },
        143 => &StatusIconInfo {
            icon: "i_dodge.tga",
            name: "Dodge",
            description: "Allows Flying Kick to be used as a counter\nWhen receiving enemy magic attack\nthere is a chance of completely avoiding it\nIf Spurt is also active\nchance of avoiding physical attacks as well",
            category: StatusCategory::Buff,
        },
        145 => &StatusIconInfo {
            icon: "i_run.tga",
            name: "Spurt",
            description: "Increases STR\nif the user is unequipped\nand the skill level is high enough",
            category: StatusCategory::Buff,
        },
        146 => &StatusIconInfo {
            icon: "캐시갑옷속성부여.tga",
            name: "%s",
            description: "Enchants Armor with Shadow Property",
            category: StatusCategory::Buff,
        },
        147 => &StatusIconInfo {
            icon: "아드레날린러쉬.tga",
            name: "Full Adrenaline Rush",
            description: "Increases Weapon ASPD except Bows",
            category: StatusCategory::Buff,
        },
        148 => &StatusIconInfo {
            icon: "i_p_tele.tga",
            name: "Warm Wind",
            description: "Enchants Weapon with Ghost Property",
            category: StatusCategory::Buff,
        },
        150 => &StatusIconInfo {
            icon: "plusattackpower.tga",
            name: "%s",
            description: "Increases ATK",
            category: StatusCategory::Buff,
        },
        151 => &StatusIconInfo {
            icon: "plusmagicpower.tga",
            name: "%s",
            description: "Increases MATK",
            category: StatusCategory::Buff,
        },
        156 => &StatusIconInfo {
            icon: "i_kaizel.tga",
            name: "Kaizel",
            description: "Cast time not affected by DEX\nUpon death, you will revive with Kyrie Eleison for 2 seconds",
            category: StatusCategory::Buff,
        },
        157 => &StatusIconInfo {
            icon: "i_kaahi.tga",
            name: "Kaahi",
            description: "Whenever you are hit by non-skills\nSP is consumed and HP is recovered",
            category: StatusCategory::Buff,
        },
        158 => &StatusIconInfo {
            icon: "i_kaupe.tga",
            name: "Kaupe",
            description: "Chance to evade an enemy attack.",
            category: StatusCategory::Buff,
        },
        161 => &StatusIconInfo {
            icon: "i_onehand.tga",
            name: "One-hand Quicken",
            description: "Using One-handed Weapon\nIncreases ASPD",
            category: StatusCategory::Buff,
        },
        169 => &StatusIconInfo {
            icon: "i_suncomfort.tga",
            name: "Comfort of the Sun",
            description: "Improves VIT DEF",
            category: StatusCategory::Buff,
        },
        170 => &StatusIconInfo {
            icon: "i_mooncomfort.tga",
            name: "Comfort of the Moon",
            description: "Improves FLEE",
            category: StatusCategory::Buff,
        },
        171 => &StatusIconInfo {
            icon: "i_starcomfort.tga",
            name: "Comfort of the Stars",
            description: "Increases ASPD",
            category: StatusCategory::Buff,
        },
        181 => &StatusIconInfo {
            icon: "i_프리저브.tga",
            name: "Preserve",
            description: "Allows you to keep copied skill",
            category: StatusCategory::Buff,
        },
        182 => &StatusIconInfo {
            icon: "i_체이스힘.tga",
            name: "%s",
            description: "Increases STR",
            category: StatusCategory::Buff,
        },
        186 => &StatusIconInfo {
            icon: "i_더블캐스팅.tga",
            name: "Double Casting",
            description: "When casting a Bolt Skill\nthere is a chance to cast another automatically",
            category: StatusCategory::Buff,
        },
        188 => &StatusIconInfo {
            icon: "i_오버맥스.tga",
            name: "Maximum Over Thrust",
            description: "Increases weapon damage.\nIncreases the possibility of breaking the weapon.",
            category: StatusCategory::Buff,
        },
        191 => &StatusIconInfo {
            icon: "i_타로카드.tga",
            name: "Tarot Card of Fate",
            description: "Applies one of 14 cards and their effects",
            category: StatusCategory::Buff,
        },
        197 => &StatusIconInfo {
            icon: "i_shrink.tga",
            name: "Shrink",
            description: "When Autoguarding attacks\nthere is a chance to push the attack back",
            category: StatusCategory::Buff,
        },
        198 => &StatusIconInfo {
            icon: "i_sightblaster.tga",
            name: "Sight Blaster",
            description: "Attacks an enemy with a single attack\nthat ventures too close",
            category: StatusCategory::Buff,
        },
        200 => &StatusIconInfo {
            icon: "i_closeconfine.tga",
            name: "Close Confine",
            description: "Both Players cannot Move\nIncreases FLEE\nDoes not affect boss monsters",
            category: StatusCategory::Buff,
        },
        201 => &StatusIconInfo {
            icon: "i_closeconfine.tga",
            name: "Close Confine",
            description: "Both Players cannot Move\nIncreases FLEE\nDoes not affect Boss",
            category: StatusCategory::Buff,
        },
        203 => &StatusIconInfo {
            icon: "i_madness.tga",
            name: "Madness Canceller (Last Stand)",
            description: "Increases ATK\nIncreases Attack Speed\nImmobilized",
            category: StatusCategory::Buff,
        },
        204 => &StatusIconInfo {
            icon: "i_fever.tga",
            name: "Gatling Fever",
            description: "Increases Damage and ASPD\nReduces Movement Speed",
            category: StatusCategory::Buff,
        },
        205 => &StatusIconInfo {
            icon: "글로리아.tga",
            name: "Happy Break (Enjoyable Rest)",
            description: "When sitting with another Taekwon\nA certain amount of SP is regained\nChance for Earth Spike scrolls to not be destroyed when used",
            category: StatusCategory::Buff,
        },
        206 => &StatusIconInfo {
            icon: "i_maemi.tga",
            name: "Cicada Skin Shedding",
            description: "Avoids a certain number of physical attacks\nWhen avoiding, move in the opposite direction of the attacker",
            category: StatusCategory::Buff,
        },
        207 => &StatusIconInfo {
            icon: "i_bunsin.tga",
            name: "Illusionary Shadow",
            description: "Avoids a certain number of physical attacks\nMagical attacks cannot be avoided",
            category: StatusCategory::Buff,
        },
        208 => &StatusIconInfo {
            icon: "i_nen.tga",
            name: "Soul",
            description: "Increases INT, STR",
            category: StatusCategory::Buff,
        },
        209 => &StatusIconInfo {
            icon: "i_adjustment.tga",
            name: "Adjustment",
            description: "Reduces HIT\nIncreases FLEE\nReduces damage of incoming ranged physical attacks",
            category: StatusCategory::Buff,
        },
        210 => &StatusIconInfo {
            icon: "i_accuracy",
            name: "Increasing Accuracy (Increase Accuracy)",
            description: "Increases Accuracy\nIncreases DEX\nIncreases AGI",
            category: StatusCategory::Buff,
        },
        217 => &StatusIconInfo {
            icon: "라이딩.tga",
            name: "Riding Griffon",
            description: "",
            category: StatusCategory::Toggle,
        },
        241 => &StatusIconInfo {
            icon: "str_gogi.tga",
            name: "%s",
            description: "Increases STR",
            category: StatusCategory::Buff,
        },
        242 => &StatusIconInfo {
            icon: "agi_gogi.tga",
            name: "%s",
            description: "Increases AGI",
            category: StatusCategory::Buff,
        },
        243 => &StatusIconInfo {
            icon: "vit_gogi.tga",
            name: "%s",
            description: "Increases VIT",
            category: StatusCategory::Buff,
        },
        244 => &StatusIconInfo {
            icon: "dex_gogi.tga",
            name: "%s",
            description: "Increases DEX",
            category: StatusCategory::Buff,
        },
        245 => &StatusIconInfo {
            icon: "int_gogi.tga",
            name: "%s",
            description: "Increases INT",
            category: StatusCategory::Buff,
        },
        246 => &StatusIconInfo {
            icon: "luk_gogi.tga",
            name: "%s",
            description: "Increases LUK",
            category: StatusCategory::Buff,
        },
        247 => &StatusIconInfo {
            icon: "gogi.tga",
            name: "%s",
            description: "Improves FLEE",
            category: StatusCategory::Buff,
        },
        248 => &StatusIconInfo {
            icon: "gogi.tga",
            name: "%s",
            description: "Improves HIT",
            category: StatusCategory::Buff,
        },
        249 => &StatusIconInfo {
            icon: "gogi.tga",
            name: "%s",
            description: "Improves CRIT",
            category: StatusCategory::Buff,
        },
        250 => &StatusIconInfo {
            icon: "exp.tga",
            name: "%s",
            description: "Increases acquired EXP",
            category: StatusCategory::Buff,
        },
        251 => &StatusIconInfo {
            icon: "death.tga",
            name: "Life Insurance",
            description: "No EXP loss upon death",
            category: StatusCategory::Buff,
        },
        252 => &StatusIconInfo {
            icon: "item.tga",
            name: "%s",
            description: "When killing monsters\nthe drop chance is doubled",
            category: StatusCategory::Buff,
        },
        271 => &StatusIconInfo {
            icon: "str_gogi.tga",
            name: "%s",
            description: "Increases STR",
            category: StatusCategory::Buff,
        },
        272 => &StatusIconInfo {
            icon: "agi_gogi.tga",
            name: "%s",
            description: "Increases AGI",
            category: StatusCategory::Buff,
        },
        273 => &StatusIconInfo {
            icon: "vit_gogi.tga",
            name: "%s",
            description: "Increases VIT",
            category: StatusCategory::Buff,
        },
        274 => &StatusIconInfo {
            icon: "dex_gogi.tga",
            name: "%s",
            description: "Increases DEX",
            category: StatusCategory::Buff,
        },
        275 => &StatusIconInfo {
            icon: "int_gogi.tga",
            name: "%s",
            description: "Increases INT",
            category: StatusCategory::Buff,
        },
        276 => &StatusIconInfo {
            icon: "luk_gogi.tga",
            name: "%s",
            description: "Increases LUK",
            category: StatusCategory::Buff,
        },
        282 => &StatusIconInfo {
            icon: "slowcast.tga",
            name: "Slow Cast",
            description: "Increases Casting Time",
            category: StatusCategory::Debuff,
        },
        286 => &StatusIconInfo {
            icon: "criticalwound.tga",
            name: "Critical Wounds",
            description: "Reduces effects of healing skills",
            category: StatusCategory::Debuff,
        },
        289 => &StatusIconInfo {
            icon: "민첩성증가.tga",
            name: "%s",
            description: "Increases Movement Speed",
            category: StatusCategory::Buff,
        },
        290 => &StatusIconInfo {
            icon: "gogi.tga",
            name: "Defense Protection",
            description: "Increases physical DEF",
            category: StatusCategory::Buff,
        },
        291 => &StatusIconInfo {
            icon: "마법방어포션.tga",
            name: "Magic Armor Potions",
            description: "Increases resistance to magical attacks",
            category: StatusCategory::Buff,
        },
        292 => &StatusIconInfo {
            icon: "중형생명수.tga",
            name: "Enhanced Healing Potion",
            description: "When healing via recovery items\nthe healing effect is increased",
            category: StatusCategory::Buff,
        },
        293 => &StatusIconInfo {
            icon: "소형생명수.tga",
            name: "Small Life Potion",
            description: "Recoverys HP every 5 seconds\nNo effect if Berserk State is active",
            category: StatusCategory::Buff,
        },
        294 => &StatusIconInfo {
            icon: "중형생명수.tga",
            name: "Medium Life Potion",
            description: "Recovers HP every 4 seconds\nNo effect if Berserk State is active",
            category: StatusCategory::Buff,
        },
        295 => &StatusIconInfo {
            icon: "스트라이킹.tga",
            name: "Varnish",
            description: "Increases Critical",
            category: StatusCategory::Buff,
        },
        298 => &StatusIconInfo {
            icon: "plusmagicpower.tga",
            name: "%s",
            description: "Max SP increased, SP consumption reduced",
            category: StatusCategory::Buff,
        },
        301 => &StatusIconInfo {
            icon: "소형생명수.tga",
            name: "Resistance Potion",
            description: "Increases resistance to\nStun, Frozen, Stone, Sleep, Silence\nBlind, Curse, Poison, Bleeding, Confusion",
            category: StatusCategory::Buff,
        },
        302 => &StatusIconInfo {
            icon: "캐시갑옷속성부여.tga",
            name: "Armor Property",
            description: "Changes your Elemental Property",
            category: StatusCategory::Buff,
        },
        304 => &StatusIconInfo {
            icon: "npc_hellpower.tga",
            name: "Hell Power",
            description: "Can not be revived\nSacrifice is Disabled\nToken of Siegfried disabled",
            category: StatusCategory::Buff,
        },
        312 => &StatusIconInfo {
            icon: "job.tga",
            name: "%s",
            description: "Increases Job EXP acquired.",
            category: StatusCategory::Buff,
        },
        313 => &StatusIconInfo {
            icon: "icon06.tga",
            name: "%s",
            description: "Increases Flee Rate",
            category: StatusCategory::Buff,
        },
        314 => &StatusIconInfo {
            icon: "death.tga",
            name: "Guardian Angel",
            description: "No EXP loss upon death",
            category: StatusCategory::Buff,
        },
        316 => &StatusIconInfo {
            icon: "rk_enchant.tga",
            name: "Enchant Blade",
            description: "Adds magic damage to physical attacks",
            category: StatusCategory::Buff,
        },
        318 => &StatusIconInfo {
            icon: "rk_nauthiz.tga",
            name: "Rune Stone: Refresh",
            description: "Removes all debuffs when cast\nGrants immunity to debuffs\nRecovers a certain amount of HP",
            category: StatusCategory::Buff,
        },
        319 => &StatusIconInfo {
            icon: "rk_turisuss.tga",
            name: "Rune Stone: Giant Growth",
            description: "Increases STR\nThere is a chance to vastly increase damage\nof close range physical attacks\nChance to destroy weapon with each hit",
            category: StatusCategory::Buff,
        },
        320 => &StatusIconInfo {
            icon: "rk_hagalaz.tga",
            name: "Rune Stone: Stone Hard Skin",
            description: "Resists damage equal to the HP consumed when casting\nPlayers that attack you with weapons\nwill break them by chance.\nOn monsters, they will have reduced ATK for 10 seconds",
            category: StatusCategory::Buff,
        },
        321 => &StatusIconInfo {
            icon: "rk_isha.tga",
            name: "Rune Stone: Vitality Activation",
            description: "To the caster,\nIncreases Healing skills and Item effects\nStops SP regeneration\nReduces SP recovery item effects",
            category: StatusCategory::Buff,
        },
        322 => &StatusIconInfo {
            icon: "rk_eisir.tga",
            name: "Rune Stone: Fighting Spirit",
            description: "Increases ATK\nIncreases ASPD of caster",
            category: StatusCategory::Buff,
        },
        323 => &StatusIconInfo {
            icon: "rk_uruz.tga",
            name: "Rune Stone: Abundance",
            description: "Recovers SP every 10 seconds",
            category: StatusCategory::Buff,
        },
        333 => &StatusIconInfo {
            icon: "포이즈닝웨폰.tga",
            name: "Cloaking Exceed",
            description: "Hides from Insects and Demon types too.\nRemains hidden until a certain number of hits received.\nIncreases Movement Speed",
            category: StatusCategory::Buff,
        },
        334 => &StatusIconInfo {
            icon: "할루시네이션워크.tga",
            name: "Hallucination Walk",
            description: "Improves Evasion Rate\nChance to evade Magical Damage.",
            category: StatusCategory::Buff,
        },
        336 => &StatusIconInfo {
            icon: "레노바티오.tga",
            name: "Renovatio",
            description: "Recovers HP every 5 seconds\nWhen used on Undead monsters\nit deals high damage according to skill level",
            category: StatusCategory::Buff,
        },
        337 => &StatusIconInfo {
            icon: "웨폰블로킹.tga",
            name: "Weapon Blocking",
            description: "When hit by close range physical attacks\nthere is a chance to nullify the damage",
            category: StatusCategory::Buff,
        },
        341 => &StatusIconInfo {
            icon: "포이즈닝웨폰.tga",
            name: "Poisoning Weapon",
            description: "Applies the poison coated on your weapon to the target",
            category: StatusCategory::Buff,
        },
        342 => &StatusIconInfo {
            icon: "신경마비독.tga",
            name: "Toxin",
            description: "Interferes with skills every 10 seconds\nPhen card is ignored\nEvery 10 seconds, SP is consumed",
            category: StatusCategory::Buff,
        },
        343 => &StatusIconInfo {
            icon: "감각마비독.tga",
            name: "Paralyze",
            description: "Reduces Attack Speed\nReduces FLEE\nReduces Movement Speed",
            category: StatusCategory::Buff,
        },
        344 => &StatusIconInfo {
            icon: "쇠약독.tga",
            name: "Venom Bleed",
            description: "Reduces Max HP",
            category: StatusCategory::Debuff,
        },
        345 => &StatusIconInfo {
            icon: "웃음버섯.tga",
            name: "Magic Mushroom (Laughing Poison Mushroom)",
            description: "Uses Smile Emoticon\nCasts random spells every 4 seconds\nDrains HP every 4 seconds",
            category: StatusCategory::Buff,
        },
        346 => &StatusIconInfo {
            icon: "상처오염독.tga",
            name: "Death Hurt (Contaminated Wound Poison)",
            description: "Reduces effects of healing skills",
            category: StatusCategory::Debuff,
        },
        347 => &StatusIconInfo {
            icon: "열병독.tga",
            name: "Pyrexia",
            description: "Dark and Hallucinating state",
            category: StatusCategory::Buff,
        },
        348 => &StatusIconInfo {
            icon: "망각의재.tga",
            name: "Oblivion Curse",
            description: "Oblivion status",
            category: StatusCategory::Debuff,
        },
        349 => &StatusIconInfo {
            icon: "거머리.tga",
            name: "Leech End",
            description: "Drains HP every second",
            category: StatusCategory::Buff,
        },
        351 => &StatusIconInfo {
            icon: "frostmisty.tga",
            name: "Freezing Status",
            description: "Decreases Defense, ASPD and Movement speed\nIncreases Fixed Cast time.",
            category: StatusCategory::Debuff,
        },
        352 => &StatusIconInfo {
            icon: "ra_fearbreeze.tga",
            name: "Fear Breeze",
            description: "When attacking with a bow\nthere is a chance to cause additional attacks",
            category: StatusCategory::Buff,
        },
        354 => &StatusIconInfo {
            icon: "marshofabyss.tga",
            name: "Marsh of Abyss",
            description: "Slows Movement\nReduces DEF, Flee",
            category: StatusCategory::Debuff,
        },
        355 => &StatusIconInfo {
            icon: "recognizespell.tga",
            name: "Recognized Spell",
            description: "Magic Skills deals Max Damage\nAll skills consumes more SP",
            category: StatusCategory::Buff,
        },
        357 => &StatusIconInfo {
            icon: "wolfmount.tga",
            name: "Warg Rider",
            description: "Bows are Disabled\nWarg Skills are only allowed",
            category: StatusCategory::Buff,
        },
        361 => &StatusIconInfo {
            icon: "엑셀레이션.tga",
            name: "Acceleration",
            description: "Increases movement speed of the Magic Gear",
            category: StatusCategory::Buff,
        },
        362 => &StatusIconInfo {
            icon: "호버링.tga",
            name: "Hovering",
            description: "Traps and some ground skills do not have any effect",
            category: StatusCategory::Buff,
        },
        368 => &StatusIconInfo {
            icon: "mvpcard_taogunka.tga",
            name: "Tao Gunka Scroll",
            description: "Increases Max HP\nReduces DEF/MDEF",
            category: StatusCategory::Buff,
        },
        369 => &StatusIconInfo {
            icon: "mvpcard_mistress.tga",
            name: "Mistress Scroll",
            description: "Nullify the Gemstone requirement of certain spells\nIncreases SP consumption",
            category: StatusCategory::Buff,
        },
        370 => &StatusIconInfo {
            icon: "mvpcard_orchero.tga",
            name: "Orc Hero Scroll",
            description: "Immunity to stun status",
            category: StatusCategory::Buff,
        },
        371 => &StatusIconInfo {
            icon: "mvpcard_orclord.tga",
            name: "Orc Lord Scroll",
            description: "Reflects a part of physical damage taken",
            category: StatusCategory::Buff,
        },
        373 => &StatusIconInfo {
            icon: "오버히트.tga",
            name: "Over Heat",
            description: "Heating caused by skill use\nDrains HP every second",
            category: StatusCategory::Buff,
        },
        374 => &StatusIconInfo {
            icon: "셰이프쉬프트.tga",
            name: "Shape Shift",
            description: "Changes your Mado Gear elemental property",
            category: StatusCategory::Buff,
        },
        375 => &StatusIconInfo {
            icon: "인프라레드스캔.tga",
            name: "Infrared Scan",
            description: "Discovers targets in hiding\nChance to Reduce FLEE of nearby enemy",
            category: StatusCategory::Buff,
        },
        377 => &StatusIconInfo {
            icon: "뉴트럴배리어.tga",
            name: "Neutral Barrier",
            description: "DEF/MDEF up\nNeutralizes ranged attacks",
            category: StatusCategory::Buff,
        },
        379 => &StatusIconInfo {
            icon: "스텔스필드.tga",
            name: "Stealth Field",
            description: "Cloaks everyone in a radius around caster\nConsumes SP while active\nReduces Movement Speed",
            category: StatusCategory::Buff,
        },
        381 => &StatusIconInfo {
            icon: "efst_atk.tga",
            name: "Manuk's Golden Chance",
            description: "Increase physical attack against\nall monsters in Manuk fields",
            category: StatusCategory::Buff,
        },
        382 => &StatusIconInfo {
            icon: "efst_def.tga",
            name: "Manuk's Will",
            description: "Decrease physical/magical damage\nfrom the monsters in Manuk field",
            category: StatusCategory::Buff,
        },
        383 => &StatusIconInfo {
            icon: "efst_atk.tga",
            name: "Pinguicula's Pickled Fruit",
            description: "Increase physical ATK against\nall monsters in Splendid fields",
            category: StatusCategory::Buff,
        },
        384 => &StatusIconInfo {
            icon: "efst_def.tga",
            name: "Honey Jam",
            description: "Decrease Physical, Magical damage received\nfrom the monsters in Splendid field",
            category: StatusCategory::Buff,
        },
        385 => &StatusIconInfo {
            icon: "리프로듀스.tga",
            name: "Reproduce",
            description: "Activates when targetted by a skill\nOnly one skill can be learnt",
            category: StatusCategory::Buff,
        },
        386 => &StatusIconInfo {
            icon: "efst_matk.tga",
            name: "Manuk's Faith",
            description: "Increase Magical attack against\nall monsters in Manuk Field",
            category: StatusCategory::Buff,
        },
        387 => &StatusIconInfo {
            icon: "efst_matk.tga",
            name: "Cornus's Tear",
            description: "Increase Magical attack against\nall monsters in Splendide fields",
            category: StatusCategory::Buff,
        },
        388 => &StatusIconInfo {
            icon: "str_gogi.tga",
            name: "%s",
            description: "Increases STR",
            category: StatusCategory::Buff,
        },
        389 => &StatusIconInfo {
            icon: "int_gogi.tga",
            name: "%s",
            description: "Increases INT",
            category: StatusCategory::Buff,
        },
        390 => &StatusIconInfo {
            icon: "lg_reflectdamage.tga",
            name: "Reflect Damage",
            description: "Reflects some of the damages received to all enemies in an area\nConsumes SP every second",
            category: StatusCategory::Toggle,
        },
        391 => &StatusIconInfo {
            icon: "포스오브뱅가드.tga",
            name: "Force of Vanguard",
            description: "Max HP, Defense increased\nWhen physicalled attacked there is a chance to earn a rage counter\nSP consumed while active",
            category: StatusCategory::Buff,
        },
        393 => &StatusIconInfo {
            icon: "오토쉐도우스펠.tga",
            name: "Auto Shadow Spell",
            description: "Automatically casts\nan available magic spell",
            category: StatusCategory::Buff,
        },
        394 => &StatusIconInfo {
            icon: "쉐도우폼.tga",
            name: "Shadow Form",
            description: "For a certain number of hits\nhave a target take the damage instead",
            category: StatusCategory::Buff,
        },
        396 => &StatusIconInfo {
            icon: "lg_shieldspell_쨔챈.tga",
            name: "Shield Spell (DEF)",
            description: "Invokes a magical spell based on DEF",
            category: StatusCategory::Buff,
        },
        397 => &StatusIconInfo {
            icon: "lg_shieldspell_쨍쨋.tga",
            name: "Shield Spell (MDEF)",
            description: "Invokes a magical spell based on MDEF",
            category: StatusCategory::Buff,
        },
        398 => &StatusIconInfo {
            icon: "lg_shieldspell_쩔짭.tga",
            name: "Shield Spell (Refine)",
            description: "Invokes a magical effect based on refine",
            category: StatusCategory::Buff,
        },
        401 => &StatusIconInfo {
            icon: "민첩성감소.tga",
            name: "Adoramus",
            description: "Blinds and reduces Movement Speed",
            category: StatusCategory::Buff,
        },
        402 => &StatusIconInfo {
            icon: "lg_prestige.tga",
            name: "Prestige",
            description: "Chance to evade Magical Attacks\nDefense Up",
            category: StatusCategory::Buff,
        },
        403 => &StatusIconInfo {
            icon: "인비지빌리티.tga",
            name: "Invisibility",
            description: "Conceals yourself from view\nAll attacks become Ghost Lvl 1 property\nDrains SP\nSkills and items cannot be used",
            category: StatusCategory::Buff,
        },
        404 => &StatusIconInfo {
            icon: "데들리인펙트.tga",
            name: "Deadly Infect",
            description: "When attacking\nor being attacked\nyour status effects are applies to them",
            category: StatusCategory::Buff,
        },
        405 => &StatusIconInfo {
            icon: "lg_banding.tga",
            name: "Banding",
            description: "Banding status",
            category: StatusCategory::Buff,
        },
        407 => &StatusIconInfo {
            icon: "lg_inspiration.tga",
            name: "Inspiration",
            description: "Hit rate, Stats, Damage, Max HP increased\nAll buffs and status effects removed\nDrains HP, SP over time\nCannot receive status effects\nLose a percentage of your EXP",
            category: StatusCategory::Buff,
        },
        408 => &StatusIconInfo {
            icon: "masquerade_enervation.tga",
            name: "Masquerade: Enervation",
            description: "Reduces ATK\nRemoves Spirit Spheres",
            category: StatusCategory::Debuff,
        },
        409 => &StatusIconInfo {
            icon: "masquerade_groomy.tga",
            name: "Masquerade: Gloomy",
            description: "Decreases ASPD and HIT\nForced to release mounts and any related animals.\nMounts and any related animals are disabled.",
            category: StatusCategory::Debuff,
        },
        410 => &StatusIconInfo {
            icon: "잠룡승천.tga",
            name: "Rising Dragon",
            description: "Maximum Spheres Increased\nIncreases Maximum HP/SP\nIncreases Attack Speed\nMaintains Fury State\nSlowly Drains HP per seconds",
            category: StatusCategory::Buff,
        },
        411 => &StatusIconInfo {
            icon: "masquerade_ignorance.tga",
            name: "Masquerade: Ignorance",
            description: "Lost a certain amount of SP\nSkills and Magics are disabled",
            category: StatusCategory::Debuff,
        },
        412 => &StatusIconInfo {
            icon: "masquerade_laziness.tga",
            name: "Masquerade: Laziness",
            description: "Reduces Movement Speed and FLEE\nIncreases casting time\nAdds a certain amount of SP when using a skill",
            category: StatusCategory::Debuff,
        },
        413 => &StatusIconInfo {
            icon: "icon02.tga",
            name: "Lightning Walk",
            description: "When targetted by a magic attack,\nafter a chance to avoid\nmove straight to the caster",
            category: StatusCategory::Buff,
        },
        414 => &StatusIconInfo {
            icon: "공속물약.tga",
            name: "Acaraje",
            description: "Increases HIT and ASPD",
            category: StatusCategory::Buff,
        },
        415 => &StatusIconInfo {
            icon: "masquerade_unlucky.tga",
            name: "Masquerade: Unlucky",
            description: "Reduces critical rate\nReduces perfect dodge\nUsing skills costs zeny\nDamage over time causes a certain status ailments.",
            category: StatusCategory::Debuff,
        },
        418 => &StatusIconInfo {
            icon: "masquerade_weakness.tga",
            name: "Masquerade: Weakness",
            description: "Reduces Max HP\nWhen evaded, weapon, shield is taken off.\nCannot equip weapons and shield",
            category: StatusCategory::Debuff,
        },
        419 => &StatusIconInfo {
            icon: "기리에엘레이손.tga",
            name: "Crescent Elbow",
            description: "Attempts to counter opponent's attack\nKnocks back opponent and deals damage\nYou still take some of the damage\nDoes not affect boss monsters",
            category: StatusCategory::Buff,
        },
        421 => &StatusIconInfo {
            icon: "스트립액세서리.tga",
            name: "Accessory Off Status",
            description: "Cannot Equip Accessories",
            category: StatusCategory::Debuff,
        },
        423 => &StatusIconInfo {
            icon: "gogi.tga",
            name: "Pope Cookie",
            description: "Increases ATK and MATK\nIncreases Resistance to all property.",
            category: StatusCategory::Buff,
        },
        425 => &StatusIconInfo {
            icon: "점혈구.tga",
            name: "Gentle Touch - Energy Gain",
            description: "When attacked or when attacking, there is a chance to\nearn a Spirit Sphere",
            category: StatusCategory::Buff,
        },
        426 => &StatusIconInfo {
            icon: "점혈반.tga",
            name: "Gentle Touch - Change",
            description: "Reduces DEF and MDEF\nIncreases Damage and ASPD",
            category: StatusCategory::Buff,
        },
        427 => &StatusIconInfo {
            icon: "점혈활.tga",
            name: "Gentle Touch - Revitalize",
            description: "Increases VIT, Max HP\nIncreases DEF\nIncreases natural HP Recovery\nMovement speed increased",
            category: StatusCategory::Buff,
        },
        429 => &StatusIconInfo {
            icon: "스윙댄스.tga",
            name: "Swing Dance",
            description: "Increases Movement Speed\nIncreases ASPD",
            category: StatusCategory::Buff,
        },
        430 => &StatusIconInfo {
            icon: "연인들을위한심포니.tga",
            name: "Symphony of Love",
            description: "Increases MDEF",
            category: StatusCategory::Buff,
        },
        435 => &StatusIconInfo {
            icon: "안식의자장가.tga",
            name: "Deep Sleep Status",
            description: "Increases Damage Received by 1.5 times\nRecovers HP/SP every 2 seconds",
            category: StatusCategory::Buff,
        },
        436 => &StatusIconInfo {
            icon: "순환하는자연의소리.tga",
            name: "Circle of Nature's Sound",
            description: "Consumes SP and recovers HP",
            category: StatusCategory::Buff,
        },
        437 => &StatusIconInfo {
            icon: "다이아몬드더스트.tga",
            name: "Frozen",
            description: "Movement, Attack, Skill and Items are not available\nDrains SP and HP continuously\nIncreases the damage taken caused by Maces, Axes and 2H Axes\nIncreases the damage taken caused by Wind Property spells\nReduces the damage taken caused by Daggers, Swords, 2H Swords and Arrows",
            category: StatusCategory::Debuff,
        },
        438 => &StatusIconInfo {
            icon: "수줍은하루의우울.tga",
            name: "Gloomy Day",
            description: "Increases the damage of specific skills\nReduces FLEE, ASPD",
            category: StatusCategory::Buff,
        },
        439 => &StatusIconInfo {
            icon: "마나의노래.tga",
            name: "Song of Mana",
            description: "Recovers SP every 5 seconds",
            category: StatusCategory::Buff,
        },
        441 => &StatusIconInfo {
            icon: "워그와함께춤을.tga",
            name: "Dance With Warg",
            description: "Increases ASPD\nReduces Fixed casting time",
            category: StatusCategory::Buff,
        },
        442 => &StatusIconInfo {
            icon: "풍차를향해돌격.tga",
            name: "Rush Windmill Attack",
            description: "Increases Damage",
            category: StatusCategory::Buff,
        },
        443 => &StatusIconInfo {
            icon: "마스커레이드.tga",
            name: "Echo Song",
            description: "Increases DEF",
            category: StatusCategory::Buff,
        },
        444 => &StatusIconInfo {
            icon: "하모나이즈.tga",
            name: "Harmonize",
            description: "Increases all Stats",
            category: StatusCategory::Buff,
        },
        445 => &StatusIconInfo {
            icon: "스트라이킹.tga",
            name: "Striking",
            description: "Increases Weapon damage and chance of critical",
            category: StatusCategory::Buff,
        },
        446 => &StatusIconInfo {
            icon: "워머.tga",
            name: "Warmer",
            description: "Removes Frozen/Freezing status\nImmunity to Frozen/Freezing status\nRecovers HP every 3 seconds",
            category: StatusCategory::Buff,
        },
        447 => &StatusIconInfo {
            icon: "달빛의세레나데.tga",
            name: "Moonlit Serenade",
            description: "Increases damage of magic skills",
            category: StatusCategory::Buff,
        },
        448 => &StatusIconInfo {
            icon: "새터데이나이트피버.tga",
            name: "Wild",
            description: "Decreases HP/SP per 3 seconds\nDamage increased, Defense and Evasion dropped\nSkills and items cannot be used.",
            category: StatusCategory::Debuff,
        },
        450 => &StatusIconInfo {
            icon: "애널라이즈.tga",
            name: "Analyze",
            description: "Reduces Physical and Magical Defense",
            category: StatusCategory::Buff,
        },
        451 => &StatusIconInfo {
            icon: "레라드의이슬.tga",
            name: "Lerad's Dew",
            description: "Increases Max HP",
            category: StatusCategory::Buff,
        },
        452 => &StatusIconInfo {
            icon: "멜로디오브싱크.tga",
            name: "Melody of Sink",
            description: "Increases Magical Damage\nDecreases Physical Damage",
            category: StatusCategory::Buff,
        },
        454 => &StatusIconInfo {
            icon: "언리미티드허밍보이스.tga",
            name: "Unlimited Humming Voice",
            description: "Affected target's skills\nincrease their SP consumption",
            category: StatusCategory::Buff,
        },
        461 => &StatusIconInfo {
            icon: "icon07.tga",
            name: "Cart Boost",
            description: "Increases Movement Speed",
            category: StatusCategory::Buff,
        },
        463 => &StatusIconInfo {
            icon: "가시나무덫.tga",
            name: "Thorn Trap",
            description: "Periodically applies damage",
            category: StatusCategory::Debuff,
        },
        472 => &StatusIconInfo {
            icon: "세크라멘트.tga",
            name: "Sacrament",
            description: "Reduces fixed casting time",
            category: StatusCategory::Buff,
        },
        473 => &StatusIconInfo {
            icon: "icon05.tga",
            name: "Assumptio",
            description: "Increases Defense",
            category: StatusCategory::Buff,
        },
        476 => &StatusIconInfo {
            icon: "안티매터리얼.tga",
            name: "Stomachache",
            description: "Reduces All Stats\nReduces Movement Speed\nForced to sit down once in every 10 sec\nConsume certain amount of SP for 10 sec",
            category: StatusCategory::Buff,
        },
        491 => &StatusIconInfo {
            icon: "str_gogi.tga",
            name: "Savage Roast",
            description: "Increases STR",
            category: StatusCategory::Buff,
        },
        492 => &StatusIconInfo {
            icon: "int_gogi.tga",
            name: "Wolf Blood Cocktail",
            description: "Increases INT",
            category: StatusCategory::Buff,
        },
        493 => &StatusIconInfo {
            icon: "vit_gogi.tga",
            name: "Minorous Beef Stew",
            description: "Increases VIT",
            category: StatusCategory::Buff,
        },
        494 => &StatusIconInfo {
            icon: "dex_gogi.tga",
            name: "Siroma Iced Tea",
            description: "Increases DEX",
            category: StatusCategory::Buff,
        },
        495 => &StatusIconInfo {
            icon: "agi_gogi.tga",
            name: "Drosera Herb Salad",
            description: "Increases AGI",
            category: StatusCategory::Buff,
        },
        496 => &StatusIconInfo {
            icon: "luk_gogi.tga",
            name: "Petite Tail Noodle",
            description: "Increases LUK",
            category: StatusCategory::Buff,
        },
        573 => &StatusIconInfo {
            icon: "gogi.tga",
            name: "Mora Berry",
            description: "Increases Resistance to every monsters\nin the fields near the town of Mora.",
            category: StatusCategory::Buff,
        },
        577 => &StatusIconInfo {
            icon: "세라4.tga",
            name: "Pain Killer",
            description: "No movement delay in receiving damage\nReduced damage taken",
            category: StatusCategory::Buff,
        },
        578 => &StatusIconInfo {
            icon: "중형생명수.tga",
            name: "Rapid Life-giving Water",
            description: "Recovers HP every 3 seconds\nNo effect if Berserk State is active",
            category: StatusCategory::Buff,
        },
        579 => &StatusIconInfo {
            icon: "에이라1.tga",
            name: "Vitalize Potion",
            description: "Increases ATK and MATK\nIncrease effects of heal and healing items",
            category: StatusCategory::Buff,
        },
        580 => &StatusIconInfo {
            icon: "에이라1.tga",
            name: "Light Of Regeneration",
            description: "When the summoner died\nHomunculus will sacrifice to revive the summoner",
            category: StatusCategory::Buff,
        },
        581 => &StatusIconInfo {
            icon: "에이라2.tga",
            name: "Overed Boost",
            description: "Increases ASPD and Evasion\nto a fixed amount",
            category: StatusCategory::Buff,
        },
        583 => &StatusIconInfo {
            icon: "all_odins_power.tga",
            name: "Odin's Power",
            description: "Increases ATK and MATK\nDecreases DEF and MDEF",
            category: StatusCategory::Buff,
        },
        584 => &StatusIconInfo {
            icon: "efst_atk.tga",
            name: "Style Change",
            description: "Homunculus in Fighter Style",
            category: StatusCategory::Toggle,
        },
        605 => &StatusIconInfo {
            icon: "디이터1.tga",
            name: "Magma Flow",
            description: "When receiving damage\nthere is a chance to eject magma around it",
            category: StatusCategory::Buff,
        },
        606 => &StatusIconInfo {
            icon: "디이터2.tga",
            name: "Granitic Armor",
            description: "Reduced damage taken\nLose some HP when the status ends.",
            category: StatusCategory::Buff,
        },
        607 => &StatusIconInfo {
            icon: "디이터4.tga",
            name: "Pyroclastic",
            description: "Weapon of Deeter and Owner\nChange to Fire Property\nIncreased weapon damage",
            category: StatusCategory::Buff,
        },
        608 => &StatusIconInfo {
            icon: "디이터5.tga",
            name: "Volcanic Ash",
            description: "Reduced hit rate\nSkill has a chance of failing\nIncreases fire damage taken",
            category: StatusCategory::Debuff,
        },
        611 => &StatusIconInfo {
            icon: "plusmagicpower.tga",
            name: "Magic Candy",
            description: "Increases MATK\nReduced fixed casting time.\nCasting cannot be interrupted.\nDrains SP every 10 seconds",
            category: StatusCategory::Buff,
        },
        613 => &StatusIconInfo {
            icon: "라이딩.tga",
            name: "Riding",
            description: "",
            category: StatusCategory::Toggle,
        },
        618 => &StatusIconInfo {
            icon: "item.tga",
            name: "Maldango Canned Cat",
            description: "When killing monsters in Maldango\nIncreases Base and Job EXP\nIncreases Item drop rate",
            category: StatusCategory::Buff,
        },
        621 => &StatusIconInfo {
            icon: "변신.tga",
            name: "Monster Transformation",
            description: "Transformed into monster.",
            category: StatusCategory::Buff,
        },
        622 => &StatusIconInfo {
            icon: "앉기.tga",
            name: "Sit",
            description: "",
            category: StatusCategory::Toggle,
        },
        636 => &StatusIconInfo {
            icon: "job.tga",
            name: "%s",
            description: "Increases gained Job experience",
            category: StatusCategory::Buff,
        },
        646 => &StatusIconInfo {
            icon: "meikyousisui.tga",
            name: "Pure Soul",
            description: "Recovers a certain amount of HP\nRecovers a certain amount of SP\nUnable to move\nChance to ignore damage when attacked\nEffect wears off by chance when hit.",
            category: StatusCategory::Buff,
        },
        647 => &StatusIconInfo {
            icon: "aspdcash.tga",
            name: "ASPD Reinforce Potion",
            description: "Increase Attack Speed",
            category: StatusCategory::Buff,
        },
        652 => &StatusIconInfo {
            icon: "izayoi.tga",
            name: "16th Night",
            description: "Removes Fixed casting time\nReduced variable casting time\nIncreases MATK\nDrains SP per second",
            category: StatusCategory::Buff,
        },
        654 => &StatusIconInfo {
            icon: "kg_kagehumi.tga",
            name: "Shadow Step",
            description: "Unable to move\nCannot use certain skills or item\nStealth or teleport skills and items are disabled.\nUnable to use Emergency Call skill",
            category: StatusCategory::Debuff,
        },
        655 => &StatusIconInfo {
            icon: "kyomu.tga",
            name: "Kyomu",
            description: "Reflects wont take effect when hit by Physical or Magical Attacks\nChance the skill will fail when casting",
            category: StatusCategory::Debuff,
        },
        656 => &StatusIconInfo {
            icon: "kagemusya.tga",
            name: "Shadow Warrior",
            description: "Enchanted with Double Attack effect\nDrains SP per second\nStatus ends when received a certain number of hits.",
            category: StatusCategory::Buff,
        },
        657 => &StatusIconInfo {
            icon: "zangetsu.tga",
            name: "Distorted Crescent Moon",
            description: "ATK and MATK changed, depending on HP and SP",
            category: StatusCategory::Buff,
        },
        659 => &StatusIconInfo {
            icon: "gensou.tga",
            name: "Oboro Gensou",
            description: "Randomly increase/decrease HP and SP\nWhen hit by Magical Attacks half of the damage\nwill be distributed around the area",
            category: StatusCategory::Buff,
        },
        660 => &StatusIconInfo {
            icon: "akaitsuki.tga",
            name: "Ominous Crimson Moonlight",
            description: "When receiving recovery skills\nhealed amount will be converted to damage.",
            category: StatusCategory::Debuff,
        },
        670 => &StatusIconInfo {
            icon: "중형생명수.tga",
            name: "Mysterious Life Potion",
            description: "Recovers a certain amount of HP every 3 seconds\nNo effect on Berserk status.",
            category: StatusCategory::Buff,
        },
        675 => &StatusIconInfo {
            icon: "flower_leaf.tga",
            name: "ÃÂ³Â¼ÂºÃÃ Â²ÃÂ°Â¡ÃÃ¶",
            description: "Increases FLEE\nIncreases perfect dodge",
            category: StatusCategory::Buff,
        },
        676 => &StatusIconInfo {
            icon: "all_ray_of_protection.tga",
            name: "RAY_OF_PROTECTION",
            description: "",
            category: StatusCategory::Buff,
        },
        677 => &StatusIconInfo {
            icon: "glastheim_atk.tga",
            name: "GLASTHEIM_ATK",
            description: "",
            category: StatusCategory::Buff,
        },
        678 => &StatusIconInfo {
            icon: "glastheim_def.tga",
            name: "GLASTHEIM_DEF",
            description: "",
            category: StatusCategory::Buff,
        },
        679 => &StatusIconInfo {
            icon: "glastheim_heal.tga",
            name: "GLASTHEIM_HEAL",
            description: "",
            category: StatusCategory::Buff,
        },
        695 => &StatusIconInfo {
            icon: "ArrowN.tga",
            name: "CLIENT_ONLY_EQUIP_ARROW",
            description: "",
            category: StatusCategory::Buff,
        },
        715 => &StatusIconInfo {
            icon: "frigg_song.tga",
            name: "FRIGG_SONG",
            description: "",
            category: StatusCategory::Buff,
        },
        720 => &StatusIconInfo {
            icon: "full_throttle.tga",
            name: "FULL_THROTTLE",
            description: "",
            category: StatusCategory::Buff,
        },
        730 => &StatusIconInfo {
            icon: "darkcrow.tga",
            name: "DARKCROW",
            description: "",
            category: StatusCategory::Buff,
        },
        _ => return None,
    };
    Some(info)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn looks_up_buff_and_debuff_icons() {
        let blessing = status_icon_info(10).expect("Blessing has an icon");
        assert_eq!(blessing.name, "Blessing");
        assert_eq!(blessing.category, StatusCategory::Buff);
        assert!(blessing.icon.ends_with(".tga"));

        let dec_agi = status_icon_info(13).expect("Decrease Agility has an icon");
        assert_eq!(dec_agi.category, StatusCategory::Debuff);

        assert!(status_icon_info(-1).is_none());
    }
}
